// Traduzione inglese dei testi dello schema dell'immobile (propertyFields) e dei criteri del punteggio (listingScore),
// per la piattaforma in inglese. I valori salvati restano in italiano (es. "Vendita"): si traduce solo cio' che si vede.
export const FIELD_EN: Record<string, string> = {
  'Contratto': 'Contract', 'Tipologia': 'Property type', 'Indirizzo': 'Address', 'Via Roma 12, Milano': '12 Via Roma, Milan',
  "Mostra l'indirizzo esatto nell'annuncio": 'Show the exact address in the listing', 'Se spento mostriamo solo zona e città.': 'If off, we only show the area and city.',
  'Prezzo': 'Price', 'Trattativa riservata': 'Price on request', 'Superficie commerciale': 'Floor area', 'Locali': 'Rooms', 'Camere da letto': 'Bedrooms', 'Bagni': 'Bathrooms', 'Piano': 'Floor',
  'Stato ed edificio': 'Condition and building', 'Lo stato è tra i primi filtri usati da chi cerca.': 'Condition is one of the first filters buyers use.', 'Stato': 'Condition',
  'Anno di costruzione': 'Year built', "Piani dell'edificio": 'Floors in the building', 'Ascensore': 'Lift', 'Tipo di proprietà': 'Ownership type',
  'Energia e impianti': 'Energy and systems', 'La classe energetica è obbligatoria per legge negli annunci.': 'The energy class is required by law in listings.',
  'Classe energetica': 'Energy class', 'Indice prestazione energetica (IPE)': 'Energy performance index (EPI)', 'Riscaldamento': 'Heating', 'Alimentazione': 'Fuel',
  'Terminali': 'Emitters', 'Aria condizionata': 'Air conditioning', 'Infissi': 'Windows', 'Materiale infissi': 'Window frames',
  'Interni': 'Interior', 'Qui nascono i dettagli che fanno la differenza nella descrizione.': 'The details that make the description stand out.',
  'Cucina': 'Kitchen', 'Arredamento': 'Furnishing', 'Esposizione': 'Exposure', 'Dotazioni': 'Features',
  'Esterni e pertinenze': 'Outdoor and extras', 'Balconi, box e cantine sono tra le ricerche più usate.': 'Balconies, garages and cellars are among the most searched features.',
  'Spazi esterni': 'Outdoor spaces', 'Superficie esterna': 'Outdoor area', 'Box o posto auto': 'Garage or parking', 'Cantina': 'Cellar',
  'Condominio e costi': 'Building and costs', 'Le spese sono la domanda numero uno al telefono.': 'Running costs are the number one question on the phone.',
  'Spese condominiali': 'Service charges', '€/mese': '€/month', 'Portineria': 'Concierge', 'Accesso disabili': 'Wheelchair access',
  'Disponibilità': 'Availability', 'Chi cerca vuole sapere quando può entrare.': 'Buyers want to know when they can move in.', 'Tipo di contratto': 'Lease type',
  'Cauzione': 'Deposit', 'mensilità': 'months', 'Spese condominiali incluse nel canone': 'Service charges included in the rent',
  'Riferimenti e media': 'References and media', "Facoltativi, utili per ritrovare l'annuncio.": 'Optional, useful to find the listing again.',
  'Codice di riferimento': 'Reference code', 'es. RIF-1024': 'e.g. REF-1024', 'Link virtual tour o video': 'Virtual tour or video link',
  'Vendita': 'Sale', 'Affitto': 'Rent', 'Appartamento': 'Apartment', 'Attico': 'Penthouse', 'Mansarda': 'Attic', 'Loft': 'Loft', 'Villa': 'Villa',
  'Villetta a schiera': 'Terraced house', 'Casa indipendente': 'Detached house', 'Terratetto': 'Townhouse', 'Rustico / Casale': 'Farmhouse',
  'Seminterrato': 'Basement', 'Piano terra': 'Ground floor', 'Rialzato': 'Raised ground floor', '1°': '1st', '2°': '2nd', '3°': '3rd', '4°': '4th', '5°': '5th',
  '6° o superiore': '6th or higher', 'Ultimo piano': 'Top floor', 'Su più livelli': 'Multi-level',
  'Nuovo / In costruzione': 'New / Under construction', 'Ottimo / Ristrutturato': 'Excellent / Renovated', 'Buono / Abitabile': 'Good / Habitable', 'Da ristrutturare': 'To renovate',
  'Intera proprietà': 'Full ownership', 'Nuda proprietà': 'Bare ownership', 'Parziale proprietà': 'Partial ownership', 'In attesa': 'Pending',
  'Autonomo': 'Independent', 'Centralizzato': 'Central', 'Assente': 'None', 'Metano': 'Natural gas', 'Pompa di calore': 'Heat pump', 'Teleriscaldamento': 'District heating',
  'Gasolio': 'Heating oil', 'GPL': 'LPG', 'Elettrico': 'Electric', 'Radiatori': 'Radiators', 'A pavimento': 'Underfloor', 'Fan coil': 'Fan coil',
  'Autonoma': 'Independent', 'Centralizzata': 'Central', 'Predisposizione': 'Pre-installed',
  'Doppio vetro': 'Double glazing', 'Triplo vetro': 'Triple glazing', 'Vetro singolo': 'Single glazing', 'Legno': 'Wood', 'PVC': 'PVC', 'Alluminio': 'Aluminium', 'Legno / Alluminio': 'Wood / Aluminium',
  'Abitabile': 'Eat-in', 'A vista': 'Open', 'Angolo cottura': 'Kitchenette', 'Cucinotto': 'Small kitchen',
  'Arredato': 'Furnished', 'Parzialmente arredato': 'Partly furnished', 'Non arredato': 'Unfurnished', 'Nord': 'North', 'Sud': 'South', 'Est': 'East', 'Ovest': 'West',
  'Parquet': 'Parquet', 'Porta blindata': 'Security door', "Impianto d'allarme": 'Alarm system', 'Fibra ottica': 'Fibre broadband', 'Domotica': 'Smart home', 'Camino': 'Fireplace',
  'Ripostiglio': 'Storage room', 'Cabina armadio': 'Walk-in wardrobe', 'Lavanderia': 'Laundry room', 'Taverna': 'Basement den', 'Soppalco': 'Mezzanine', 'Videocitofono': 'Video intercom',
  'Balcone': 'Balcony', 'Terrazzo': 'Terrace', 'Giardino privato': 'Private garden', 'Giardino condominiale': 'Shared garden', 'Cortile': 'Courtyard', 'Piscina': 'Pool',
  'Nessuno': 'None', 'Box singolo': 'Single garage', 'Box doppio': 'Double garage', 'Posto auto coperto': 'Covered parking', 'Posto auto scoperto': 'Open parking',
  'Intera giornata': 'Full day', 'Mezza giornata': 'Half day', 'Libero subito': 'Available now', 'Libero al rogito': 'Available on completion', 'Occupato': 'Occupied', 'Da concordare': 'To be agreed',
  '4+4': '4+4', '3+2 concordato': '3+2 agreed rent', 'Transitorio': 'Short-term', 'Per studenti': 'Student let',
  'Foto': 'Photos', 'Qualità, luce, ordine, prima foto, stanze mostrate': 'Quality, light, tidiness, first photo, rooms shown',
  'Dati della scheda': 'Listing details', "Campi che l'acquirente cerca: spese, classe, piano, riscaldamento": 'Fields buyers look for: costs, energy class, floor, heating',
  'Descrizione': 'Description', 'Completa, chiara, ben scritta, senza refusi': 'Complete, clear, well written, no typos',
  'Affidabilità': 'Reliability', 'Dati coerenti con foto e testo, niente contatti nel testo': 'Data matches photos and text, no contacts in the text',
  'Titolo': 'Title', 'Zona per prima, tipologia precisa e un punto di forza, max 60 caratteri': 'Area first, exact property type and one selling point, max 60 characters',
  // stili e viste (StagingView, lib/staging e stagingPrompts)
  'Moderno': 'Modern', 'Nordico': 'Nordic', 'Giorno e Notte': 'Day and night', 'Svuota stanza': 'Empty the room', 'Moderna': 'Modern', 'Nordica': 'Nordic',
  'Mediterranea': 'Mediterranean', 'Mediterraneo': 'Mediterranean', 'Rinnova': 'Refresh', 'Naturale': 'Natural', 'Lussuoso': 'Luxury',
  'Notte': 'Night', 'Giorno pieno': 'Full daylight', 'Dettaglio': 'Close-up', 'Dall’alto': 'From above', 'Dal basso': 'From below', 'Grandangolo': 'Wide angle',
  'Giorno a notte': 'Day to night', 'Notte a giorno': 'Night to day',
};
