// Flussi video di GetNearMe (reel social, supabase/functions/generate-social-video), prompt copiati identici.
// Kling o3 standard image-to-video, primo e ultimo fotogramma, 5 s a clip; fotogrammi intermedi con Nano Banana.

export const GNM_STOPMOTION = "Playful stop-motion style real-estate staging animation: over 5 seconds, an invisible interior designer places furniture pieces one at a time into the empty room. Each piece pops into its exact final position with a quick scale-up appear effect, as if snapped into place. Once placed, each item stays solidly visible while the next piece pops in. Camera locked on tripod, identical framing throughout. Warm modern interior, cinematic staging reveal.";
export const GNM_PARTICLES = "Locked tripod, fixed camera angle, absolutely no camera movement. Magical particle transformation: golden dust particles swirl into the empty room and coalesce into furniture. Each piece materializes from shimmering particles that spiral inward and settle into place. Ethereal volumetric light rays stream through windows. The room geometry, walls, floor, ceiling, and windows remain perfectly static and unchanged throughout. Only the furniture materializes from glowing particles. No morphing, no warping, no camera movement. Cinematic, warm interior lighting, professional real-estate staging reveal.";
export const GNM_STRUCTURE_IMAGE = "CRITICAL: preserve the reference image pixel-for-pixel everywhere EXCEPT the main building itself. Same exact location, same camera position, same focal length, same perspective, same lighting, same time of day, same season. Reproduce identically: the exact same trees, neighboring houses, fence, gates, road, sky and clouds, landscape. ONLY modify the main building: show it in mid-construction with the same exact footprint. Bare concrete structural frame — visible columns and floor slabs. Exterior walls partially built with concrete blocks at half height. Iron rebar protrudes from column tops. Roof completely missing. Wooden scaffolding wraps the perimeter. A construction crane visible behind the building. No people. Photorealistic.";
export const GNM_EXCAVATION_IMAGE = "CRITICAL: preserve the reference image pixel-for-pixel everywhere EXCEPT the building footprint. Same exact location, same camera position, same focal length, same perspective, same lighting. Reproduce identically: the exact same trees, neighboring houses, fence, gates, road, sky. The building structure is completely absent. Show a freshly excavated foundation: a rectangular pit dug into bare dirt, wooden formwork around the perimeter, iron rebar cages, piles of gravel and sand, a small concrete mixer, portable construction fence. No building, no walls, no columns. Photorealistic.";
export const GNM_NIGHT_IMAGE = "CRITICAL: preserve the reference image pixel-for-pixel — same building, same camera position, same focal length, same perspective, same trees, same garden, same road, same cars, same fence. ONLY change the lighting to nighttime: dark sky with stars or moon, warm interior lights glowing from every window, exterior wall-wash lights illuminating the facade, subtle landscape lighting on garden paths and plants, warm ambient glow from doorways, cool blue moonlight on the roof and surroundings. The building and all objects remain identical — only the time of day changes from midday to late evening. Photorealistic night photography.";
export const GNM_DAYNIGHT = "Cinematic real-estate day-to-night time-lapse of the same building, locked tripod camera, identical framing the whole time. Over 5 seconds the sun sets: bright midday sky smoothly turns golden, then deep blue dusk, then night. Interior lights switch on warmly one room after another, exterior facade and landscape lights fade up, moon and stars appear. The building, trees, garden and cars stay perfectly still and identical — only light and time of day change. Smooth continuous transition, photorealistic.";
export const GNM_CANTIERE_1 = "Locked tripod, fixed camera, absolutely no camera movement. Construction timelapse: foundation transforms as walls rise, concrete columns appear, scaffolding goes up. Realistic construction, natural daylight. No people.";
export const GNM_CANTIERE_2 = "Locked tripod, fixed camera, absolutely no camera movement. Construction timelapse: structure completes as roof is installed, walls finished, windows placed, scaffolding removed, final paint and landscaping. Natural daylight. No people.";

// Interni (29/09): giorno e notte di una stanza e movimento di camera su una foto
export const NIGHT_IMAGE_INTERIOR = "CRITICAL: preserve the reference image pixel-for-pixel: same room, same camera position, same focal length, same framing, same furniture, objects, walls, floor and windows in the same places. ONLY change the time of day to evening: outside the windows a deep blue dusk sky, and inside every lamp, ceiling light, pendant and LED strip that exists in the room switched on with a warm glow, soft pools of warm light on the walls and floor, cosy evening atmosphere. Do not add new lamps or objects. Photorealistic interior night photography.";
export const DAYNIGHT_INTERIOR = "Cinematic real-estate day-to-evening time-lapse inside the same room, locked tripod camera, identical framing the whole time. Over 5 seconds the daylight through the windows fades to golden, then deep blue dusk, while the room's lamps and ceiling lights switch on one after another with a warm glow. Furniture, walls, floor and every object stay perfectly still and identical: only light and time of day change. Smooth continuous transition, photorealistic.";
export const CAMERA_MOVE = "Smooth cinematic real-estate video of this exact room, as filmed with a gimbal: the camera glides slowly and steadily forward into the room with a gentle, subtle parallax, at constant speed, no shake, no cuts. The room, furniture, walls, windows, light and every object stay exactly as in the photo: nothing moves, appears, disappears or changes shape. No people, no text. Photorealistic, natural daylight.";
