// Flussi video di GetNearMe (reel social, supabase/functions/generate-social-video), prompt copiati identici.
// Kling o3 standard image-to-video, primo e ultimo fotogramma, 5 s a clip; fotogrammi intermedi con Nano Banana.

export const GNM_STOPMOTION = "Playful stop-motion style real-estate staging animation: over 5 seconds, an invisible interior designer places furniture pieces one at a time into the empty room. Each piece pops into its exact final position with a quick scale-up appear effect, as if snapped into place. Once placed, each item stays solidly visible while the next piece pops in. Camera locked on tripod, identical framing throughout. Warm modern interior, cinematic staging reveal.";
export const GNM_PARTICLES = "Locked tripod, fixed camera angle, absolutely no camera movement. Magical particle transformation: golden dust particles swirl into the empty room and coalesce into furniture. Each piece materializes from shimmering particles that spiral inward and settle into place. Ethereal volumetric light rays stream through windows. The room geometry, walls, floor, ceiling, and windows remain perfectly static and unchanged throughout. Only the furniture materializes from glowing particles. No morphing, no warping, no camera movement. Cinematic, warm interior lighting, professional real-estate staging reveal.";
export const GNM_STRUCTURE_IMAGE = "CRITICAL: preserve the reference image pixel-for-pixel everywhere EXCEPT the main building itself. Same exact location, same camera position, same focal length, same perspective, same lighting, same time of day, same season. Reproduce identically: the exact same trees, neighboring houses, fence, gates, road, sky and clouds, landscape. ONLY modify the main building: show it in mid-construction with the same exact footprint. Bare concrete structural frame — visible columns and floor slabs. Exterior walls partially built with concrete blocks at half height. Iron rebar protrudes from column tops. Roof completely missing. Wooden scaffolding wraps the perimeter. A construction crane visible behind the building. No people. Photorealistic.";
export const GNM_EXCAVATION_IMAGE = "CRITICAL: preserve the reference image pixel-for-pixel everywhere EXCEPT the building footprint. Same exact location, same camera position, same focal length, same perspective, same lighting. Reproduce identically: the exact same trees, neighboring houses, fence, gates, road, sky. The building structure is completely absent. Show a freshly excavated foundation: a rectangular pit dug into bare dirt, wooden formwork around the perimeter, iron rebar cages, piles of gravel and sand, a small concrete mixer, portable construction fence. No building, no walls, no columns. Photorealistic.";
export const GNM_NIGHT_IMAGE = "CRITICAL: preserve the reference image pixel-for-pixel — same building, same camera position, same focal length, same perspective, same trees, same garden, same road, same cars, same fence. ONLY change the lighting to nighttime: dark sky with stars or moon, warm interior lights glowing from every window, exterior wall-wash lights illuminating the facade, subtle landscape lighting on garden paths and plants, warm ambient glow from doorways, cool blue moonlight on the roof and surroundings. The building and all objects remain identical — only the time of day changes from midday to late evening. Photorealistic night photography.";
export const GNM_DAYNIGHT = "Cinematic real-estate day-to-night time-lapse of the same building, locked tripod camera, identical framing the whole time. Over 5 seconds the sun sets: bright midday sky smoothly turns golden, then deep blue dusk, then night. Interior lights switch on warmly one room after another, exterior facade and landscape lights fade up, moon and stars appear. The building, trees, garden and cars stay perfectly still and identical — only light and time of day change. Smooth continuous transition, photorealistic.";
export const GNM_CANTIERE_1 = "Locked tripod, fixed camera, absolutely no camera movement. Construction timelapse: foundation transforms as walls rise, concrete columns appear, scaffolding goes up. Realistic construction, natural daylight. No people.";
export const GNM_CANTIERE_2 = "Locked tripod, fixed camera, absolutely no camera movement. Construction timelapse: structure completes as roof is installed, walls finished, windows placed, scaffolding removed, final paint and landscaping. Natural daylight. No people.";

// Interni (29/09): giorno e notte di una stanza e movimento di camera su una foto
export const NIGHT_IMAGE_INTERIOR = "CRITICAL: preserve the reference image pixel-for-pixel: same room, same camera position, same focal length, same framing, same furniture, objects, walls, floor and windows in the same places. ONLY change the time of day to evening: outside the windows a deep blue dusk sky, and inside every lamp, ceiling light, pendant and LED strip that exists in the room switched on with a warm glow, soft pools of warm light on the walls and floor, cosy evening atmosphere. Do not add new lamps or objects. Photorealistic interior night photography.";
export const DAYNIGHT_INTERIOR = "Cinematic real-estate day-to-evening time-lapse inside the same room, locked tripod camera, identical framing the whole time. Over 5 seconds the daylight through the windows fades to golden, then deep blue dusk, while the room's lamps and ceiling lights switch on one after another with a warm glow. Furniture, walls, floor and every object stay perfectly still and identical: only light and time of day change. Smooth continuous transition, photorealistic.";
// Movimento camera: prompt e negativi della "passeggiata" dei video di GetNearMe (generate-ai-video-avatar, MID ed EXT)
export const WALK_INTERIOR = 'First-person POV slowly walking forward into the room. The camera moves gently and steadily forward along the depth axis, at a calm walking pace. No rotation, no panning sideways, no tilt — only pure forward translation. The viewer is quietly exploring the space, stepping slowly into it. Realistic parallax: near objects pass by the edges of the frame, far objects grow larger naturally. Everything in the shot — walls, furniture, floor — stays physically consistent with the input photo. Do not add, remove or rearrange any furniture. Do not invent new rooms or doors beyond what is already visible. Photorealistic interior, stable geometry, slow and steady pace.';
export const WALK_INTERIOR_NEG = 'blur, distort, low quality, morphing furniture, melting walls, warping geometry, new walls, new doors, new windows, new rooms, fictional rooms, additional objects, hallucinated furniture, beyond frame, extending beyond photo, people, hands, mirror reflection of person, figure in mirror, person in mirror, ghost reflection, reflected human, deformation, color shift, texture change, quality drop, fast motion, rotation, sideways pan, tilt';
export const WALK_EXTERIOR = 'First-person POV slowly walking forward toward the property. The camera moves gently and steadily forward along the depth axis, at a calm walking pace. No rotation, no panning sideways, no tilt — only pure forward translation. The viewer is quietly approaching the building, stepping slowly toward it. Realistic parallax: near elements pass by the edges of the frame, the building and far elements grow larger naturally. Everything in the shot — building, facade, garden, trees, sky, road — stays physically consistent with the input photo. Do not add, remove or rearrange anything. Do not invent new buildings, structures or objects beyond what is already visible. Photorealistic outdoor real-estate footage, stable geometry, slow and steady pace.';
export const WALK_EXTERIOR_NEG = 'blur, distort, low quality, morphing, warping, melting building, deforming facade, new buildings, new structures, extra floors, extra windows, hallucinated objects, people, hands, moving cars, fast motion, rotation, sideways pan, tilt, orbit, drone shot, color shift, texture change';

// Ristrutturazione (05/10): dalla foto di una stanza in cantiere (muri grezzi, impianti a vista, senza pavimento) alla
// stanza finita e poi arredata. Due clip Kling di seguito, inquadratura ferma, come il Cantiere.
export const RENO_FINISHED_IMAGE = "Show this exact same room fully renovated and finished but still completely empty: smooth plastered walls painted warm white, a finished ceiling with a simple light fixture, a new floor (light oak-look parquet or large light porcelain tiles), skirting boards, finished window frames and sills, doors installed, sockets and switches mounted with Italian-style white wall plates. Remove every construction element: rubble, dust, tools, ladders, buckets, sacks, exposed pipes and cables, scaffolding, protective sheets. CRITICAL: keep exactly the same room geometry, walls, openings, windows, doors, columns, ceiling height, camera position, framing, lens and perspective as the input photo; same daylight direction. No furniture, no people, no text.";
export const RENO_FURNISHED_IMAGE = "Furnish this exact empty finished room realistically for its use, in a simple modern style typical of an Italian real estate listing: furniture in proportion, a rug, curtains, a few plants and decor. Use the second image (the same room under renovation) only to understand what the room is for: a kitchen if there are kitchen connections, a bathroom if there are sanitary drains, otherwise a living room. Same neutral daylight and white balance as the input, lamps switched off. CRITICAL: keep exactly the same walls, floor, ceiling, windows, doors, light, camera position, framing and perspective; only add furniture and decor. No people, no text.";
export const RENO_1 = "Locked tripod, fixed camera, absolutely no camera movement. Interior renovation timelapse: the rubble and tools disappear, cables and pipes go into the walls, the walls are plastered smooth and painted, the floor is laid tile by tile, the ceiling is finished, windows and doors are fitted, ending exactly on the last image of the finished empty room. Realistic, natural daylight. No people.";
export const RENO_2 = "Locked tripod, fixed camera, absolutely no camera movement. The finished empty room gets furnished: the rug rolls out, the furniture appears piece by piece in its place, then curtains, plants and decor; decor and wall art fade in already at their final size, no growing or morphing, ending exactly on the last image. Smooth, satisfying, realistic, natural daylight. No people.";

// Drone esterno (05/10): da UNA foto di esterno, ripresa come con un drone che sale e gira lentamente attorno alla casa.
// Kling 2.5 Turbo Pro da una foto (1080p), senza foto finale: l'edificio deve restare quello della foto.
export const DRONE_EXTERIOR = 'Cinematic aerial drone shot of this exact property. The camera slowly rises and smoothly orbits around the building in a gentle arc of about 30 to 45 degrees, gradually revealing its sides and the surroundings from a slightly higher viewpoint, like a professional real-estate drone video. One continuous, fluid, perfectly stable movement at constant slow speed, no cuts. The building stays exactly as in the photo: same architecture, same proportions, same roof, same colors and materials, same windows, doors and shutters in the same places. Garden, trees and surroundings stay consistent with the photo. Natural daylight, the same light and sky as the photo. Photorealistic, sharp, stable geometry.';
export const DRONE_EXTERIOR_NEG = 'blur, low quality, distortion, warping, morphing, melting building, deforming facade, building changing shape, new buildings, extra floors, extra windows, changing windows, changing colors, hallucinated objects, people, animals, cars appearing, vehicles, drone visible, fisheye, camera shake, jitter, flicker, flickering light, exposure change, fast motion, sudden movement, cut, text, watermark';

// Stagioni (05/10): stessa scena nella stagione scelta (GPT Image, come la notte del Giorno e notte), poi Kling 2.5 Turbo
// Pro primo/ultimo fotogramma tra la foto vera e quella nuova. Solo vegetazione, cielo, luce e neve cambiano.
const SEASON_KEEP = 'CRITICAL: preserve the reference image pixel-for-pixel: same building, same architecture, same camera position, same focal length, same framing, same perspective, same walls, roof, windows, doors, shutters, railings, paving, fences and furniture in the same places. Do not add or remove any building element or object. ONLY change';
export const SEASON_IMAGE: Record<'estate' | 'primavera' | 'neve', string> = {
  estate: `${SEASON_KEEP} the season to full summer: lush deep-green lawn and hedges, trees in full green leaf, colourful flowers in the beds and pots, clear bright blue sky, warm sunny midday light with soft natural shadows. Photorealistic real-estate photography.`,
  primavera: `${SEASON_KEEP} the season to spring in full bloom: fruit trees and shrubs covered in white and pink blossom, fresh bright-green lawn, spring flowers blooming in the beds and pots, a few petals on the ground, soft clear blue sky with light clouds, gentle fresh morning light. Photorealistic real-estate photography.`,
  neve: `${SEASON_KEEP} the season to a snowy winter evening: a soft layer of fresh white snow on the roof, window sills, ledges, ground, trees and plants, light snowflakes in the air, a soft blue-grey dusk sky, and warm interior lights glowing from every window with a cosy welcoming atmosphere. Photorealistic real-estate photography.`,
};
export const SEASON_VIDEO: Record<'estate' | 'primavera' | 'neve', string> = {
  estate: 'Cinematic real-estate time-lapse of the same property, locked tripod camera, identical framing the whole time. The season slowly and naturally turns to summer: the grey sky clears to bright blue, bare branches fill with fresh green leaves, the lawn grows lush and green, flowers open in the beds and pots, warm sunlight spreads over the scene. The building, walls, roof, windows and paving stay perfectly still and identical: only vegetation, sky and light change. Smooth, slow, continuous transition, photorealistic.',
  primavera: 'Cinematic real-estate time-lapse of the same property, locked tripod camera, identical framing the whole time. Spring arrives slowly and naturally: buds swell on the branches and blossom opens into white and pink flowers, the lawn turns fresh bright green, flowers bloom in the beds and pots, a few petals drift down. The building, walls, roof, windows and paving stay perfectly still and identical: only vegetation, sky and light change. Smooth, slow, continuous transition, photorealistic.',
  neve: 'Cinematic real-estate time-lapse of the same property, locked tripod camera, identical framing the whole time. Snow begins to fall gently and slowly settles, a soft white layer gradually covering the roof, ledges, ground, trees and plants, while the sky dims to a soft winter dusk and warm lights switch on in the windows. The building, walls, roof shape, windows and paving stay perfectly still and identical: only snow, sky, vegetation and light change. Smooth, slow, continuous transition, photorealistic.',
};
export const SEASON_NEG = 'camera movement, pan, zoom, camera shake, building changing shape, new buildings, extra windows, changing architecture, morphing, warping, people, animals, cars, text, watermark, flicker, cut, fast motion';
export type Season = keyof typeof SEASON_IMAGE;
