// Domande frequenti della home: mostrate nella landing e ripetute come FAQPage (JSON-LD) in src/app/[locale]/page.tsx.
export const FAQ: [string, string][] = [
  ['Perché un agente immobiliare dovrebbe usare l\'home staging virtuale?', 'Perché una casa vuota o arredata male sembra più piccola e più fredda di com\'è, e sul portale chi scorre non si ferma. Con le stanze arredate l\'acquirente si immagina dentro la casa e chiede la visita, e il proprietario vede che per la sua casa ti stai impegnando. Senza pagare né organizzare un home staging vero.'],
  ['Serve un sito personale se ci sono già i portali immobiliari?', 'Sì. Sul portale l\'acquirente sceglie la casa, non l\'agente, e accanto ci sono decine di concorrenti. Il tuo sito è l\'unico posto dove ci sei solo tu: lo mandi ai clienti, lo metti in firma, lo mostri ai proprietari quando ti giochi l\'incarico. E i contatti arrivano direttamente a te.'],
  ['Come si trovano più incarichi di vendita?', 'Il proprietario affida la casa a chi gli dimostra meglio come la venderà. Presentarti con foto arredate, un video e una pagina già pronta sul tuo sito fa la differenza rispetto a chi arriva solo con una stima. E pubblicare con costanza sui social ti rende l\'agente che la gente della zona conosce.'],
  ['Quanto costa Agente Immo?', 'Ci sono tre piani. Starter a 19 euro al mese con 900 crediti (300 foto arredate oppure da 4 a 9 video). Plus a 49 euro al mese con 1.500 crediti (500 foto oppure da 7 a 15 video) e il tuo sito compreso. Pro a 59 euro al mese con l\'annuale o 69 con il trimestrale, con 2.500 crediti (833 foto oppure da 12 a 25 video) e il sito. Puoi provarlo gratis su una tua foto direttamente dalla pagina, senza registrarti.'],
  ['Che video posso fare?', 'Sei modelli, da una foto o da un tuo video: Prima e dopo (la stanza vuota che si arreda), Cantiere e Volo nel cantiere (dal cantiere alla casa finita, per le facciate), Giorno e notte, Camminata (una ripresa lenta dentro la stanza) e Con te in video (parli in camera, esci e la stanza si arreda). Il video esce verticale o orizzontale come la foto, con la musica già scelta, in pochi minuti.'],
  ['Quanti crediti consuma ogni cosa?', 'Una foto arredata o svuotata costa 3 crediti, anche una planimetria. Le prime 3 modifiche scritte su ogni foto sono gratis, poi 1 credito. I video: Prima e dopo 100, Cantiere e Volo nel cantiere 200, Giorno e notte 40, Camminata 30, Con te in video 40. I crediti si scalano solo quando il risultato è pronto: se qualcosa non riesce non paghi.'],
  ['Quanto costa rispetto a fotografo, home stager e web agency?', 'Un home staging vero o un videomaker si pagano immobile per immobile. Con Agente Immo paghi un abbonamento e hai foto arredate, video e sito per tutti i tuoi immobili.'],
  ['E se il sito non mi serve?', 'Non devi usarlo: il sito si pubblica solo quando lo accendi tu. Foto e video funzionano lo stesso, allo stesso prezzo.'],
  ['Le foto arredate con l\'AI si possono usare negli annunci?', 'Sì. L\'AI aggiunge solo i mobili e lascia com\'è tutto il resto: muri, finestre, pavimenti e prospettiva. Per correttezza verso chi cerca casa è buona regola indicare nell\'annuncio che l\'arredamento è virtuale, e tenere anche la foto originale.'],
  ['Serve saper usare programmi di grafica o di montaggio video?', 'No. Scrivi cosa vuoi in italiano, come in una chat, oppure scegli uno stile con un clic. Foto, video e pagine del sito si preparano da sole.'],
]

// Stesse domande per la landing inglese (/en)
export const FAQ_EN: [string, string][] = [
  ['Why should a real estate agent use virtual staging?', 'Because an empty or poorly furnished home looks smaller and colder than it is, and people scrolling a portal don\'t stop. With staged rooms buyers picture themselves in the home and ask for a viewing, and the owner sees you\'re putting real effort into their property. Without paying for or organizing physical staging.'],
  ['Do I need my own website if the property portals already exist?', 'Yes. On a portal buyers choose the home, not the agent, and dozens of competitors sit right next to you. Your website is the one place where it\'s only you: send it to clients, put it in your signature, show it to owners when you pitch for a listing. And inquiries come straight to you.'],
  ['How do you win more listings?', 'Owners give their home to whoever best shows how they\'ll sell it. Showing up with staged photos, a video and a page already live on your website makes the difference against agents who only bring a valuation. And posting regularly on social media makes you the agent people in the area know.'],
  ['How much does Agente Immo cost?', 'There are three plans. Starter at €19 a month with 900 credits (300 staged photos or 4 to 9 videos). Plus at €49 a month with 1,500 credits (500 photos or 7 to 15 videos) and your website included. Pro at €59 a month billed yearly or €69 billed quarterly, with 2,500 credits (833 photos or 12 to 25 videos) and the website. You can try it free on one of your photos right from the page, no sign-up needed.'],
  ['Which videos can I make?', 'Six templates, from a photo or a video of yours: Before and after (an empty room getting furnished), Building site and Site fly-through (from the building site to the finished home, for facades), Day to night, Walk-in (a slow shot inside the room) and You on camera (you talk, walk out and the room gets furnished). The video comes out vertical or horizontal like the photo, with music already picked, in a few minutes.'],
  ['How many credits does each thing use?', 'A staged or emptied photo costs 3 credits, floor plans too. The first 3 written edits on each photo are free, then 1 credit. Videos: Before and after 100, Building site and Site fly-through 200, Day to night 40, Walk-in 30, You on camera 40. Credits are only taken when the result is ready: if something fails, you do not pay.'],
  ['How does it compare to a photographer, home stager and web agency?', 'Physical staging or a videographer are paid property by property. With Agente Immo you pay one subscription and get staged photos, videos and a website for all your properties.'],
  ['What if I don\'t need the website?', 'You don\'t have to use it: the website only goes live when you switch it on. Photos and videos work the same, at the same price.'],
  ['Can AI-staged photos be used in listings?', 'Yes. The AI only adds furniture and leaves everything else as it is: walls, windows, floors and perspective. To be fair to buyers, it\'s good practice to state in the listing that the furniture is virtual and to keep the original photo too.'],
  ['Do I need to know graphic design or video editing software?', 'No. Write what you want in plain words, like in a chat, or pick a style with one click. Photos, videos and website pages get made on their own.'],
]
