// Domande frequenti della home: mostrate nella landing e ripetute come FAQPage (JSON-LD) in src/app/[locale]/page.tsx.
export const FAQ: [string, string][] = [
  ['Perché un agente immobiliare dovrebbe usare l\'home staging virtuale?', 'Perché una casa vuota o arredata male sembra più piccola e più fredda di com\'è, e sul portale chi scorre non si ferma. Con le stanze arredate l\'acquirente si immagina dentro la casa e chiede la visita, e il proprietario vede che per la sua casa ti stai impegnando. Senza pagare né organizzare un home staging vero.'],
  ['Serve un sito personale se ci sono già i portali immobiliari?', 'Sì. Sul portale l\'acquirente sceglie la casa, non l\'agente, e accanto ci sono decine di concorrenti. Il tuo sito è l\'unico posto dove ci sei solo tu: lo mandi ai clienti, lo metti in firma, lo mostri ai proprietari quando ti giochi l\'incarico. E i contatti arrivano direttamente a te.'],
  ['Come si trovano più incarichi di vendita?', 'Il proprietario affida la casa a chi gli dimostra meglio come la venderà. Presentarti con foto arredate, un video e una pagina già pronta sul tuo sito fa la differenza rispetto a chi arriva solo con una stima. E pubblicare con costanza sui social ti rende l\'agente che la gente della zona conosce.'],
  ['Quanto costa Agente Immo?', 'Ci sono due piani con lo stesso prodotto, sito compreso. Starter a 29 euro al mese, mensile, con 1.000 crediti (circa 200 foto arredate). Pro a 59 euro al mese con l\'annuale o 69 con il trimestrale, con 2.500 crediti (circa 500 foto). Puoi provarlo gratis su una tua foto direttamente dalla pagina, senza registrarti.'],
  ['Quanto costa rispetto a fotografo, home stager e web agency?', 'Un home staging vero o un videomaker si pagano immobile per immobile. Con Agente Immo paghi un abbonamento e hai foto arredate, video e sito per tutti i tuoi immobili.'],
  ['E se il sito non mi serve?', 'Non devi usarlo: il sito si pubblica solo quando lo accendi tu. Foto e video funzionano lo stesso, allo stesso prezzo.'],
  ['Le foto arredate con l\'AI si possono usare negli annunci?', 'Sì. L\'AI aggiunge solo i mobili e lascia com\'è tutto il resto: muri, finestre, pavimenti e prospettiva. Per correttezza verso chi cerca casa è buona regola indicare nell\'annuncio che l\'arredamento è virtuale, e tenere anche la foto originale.'],
  ['Serve saper usare programmi di grafica o di montaggio video?', 'No. Scrivi cosa vuoi in italiano, come in una chat, oppure scegli uno stile con un clic. Foto, video e pagine del sito si preparano da sole.'],
]
