import { type Locale } from "./i18n";

type Block =
  | { type: "h2"; text: string }
  | { type: "h3"; text: string }
  | { type: "p"; text: string }
  | { type: "ul"; items: string[] };

interface LegalPage {
  title: string;
  lastUpdated: string;
  description: string;
  blocks: Block[];
}

export const privacyContent: Record<Locale, LegalPage> = {
  en: {
    title: "Privacy Policy",
    lastUpdated: "Last Updated: 01 February 2026",
    description: "Privacy Policy for the GetNearMe browser extension.",
    blocks: [
      { type: "h2", text: "1. Introduction and Data Controller" },
      { type: "p", text: "This Privacy Policy governs the processing of personal data in connection with the use of the GetNearMe browser extension (the \"Service\"). This Policy is intended to comply with Regulation (EU) 2016/679 (GDPR) and with Directive 2002/58/EC (ePrivacy Directive) regarding access to and storage of information on user terminal equipment." },
      { type: "p", text: "Data Controller: Antonio Scirica acting commercially under the trade name \"GetNearMe\"\nEmail: as.scirica@gmail.com" },
      { type: "h2", text: "2. Nature of Data Processing" },
      { type: "p", text: "To ensure data minimization and strictly respect third-party intellectual property rights, the Service operates primarily as a local, client-side utility." },
      { type: "ul", items: [
        "Local Processing: The analysis of real estate properties is performed dynamically within the User's browser. The Service does not index, or reproduce third-party databases on its own servers to create a competing search engine.",
        "No Data Transfer for Aggregation: Content visible on the User's screen is processed temporarily in the browser's volatile memory and is not transmitted to the Controller's servers for permanent storage or aggregation.",
        "Property-related data processed locally by the Service primarily relates to real estate objects and locations and does not typically constitute personal data of identifiable natural persons within the meaning of Article 4 GDPR."
      ]},
      { type: "h2", text: "3. Categories of Data Processed" },
      { type: "p", text: "We process only the data strictly necessary to deliver the Service, categorized by storage location:" },
      { type: "h3", text: "3.1. Server-Side Data (Account & Technical Logs)" },
      { type: "p", text: "Our backend infrastructure processes limited metadata required for account management and security:" },
      { type: "ul", items: [
        "Identity Data: Email address and User ID (authenticated via Supabase) to manage your account and subscription.",
        "Transactional Data: Subscription status, credit balance, and payment identifiers processed securely by Stripe (we do not store full credit card numbers).",
        "Technical Service Logs: Technical service validation events confirming that a requested operation was successfully executed (used strictly for credit deduction and debugging), without storing listing content or attributes.",
        "Security & Retention: IP addresses and technical logs are retained only for the limited period strictly necessary to fulfill their specific purpose (security monitoring, debugging, and service validation) and are periodically deleted in accordance with internal retention policies to comply with the principle of Storage Limitation (Art. 5(1)(e) GDPR)."
      ]},
      { type: "h3", text: "3.2. Client-Side Data (Local Device Only)" },
      { type: "p", text: "To display comparisons and contextual insights, the Service processes the following data exclusively on your device:" },
      { type: "ul", items: [
        "Temporary Session Data: The Extension utilizes the browser's Local Storage API (chrome.storage.local) to temporarily cache limited factual data necessary for analysis visible on the page required for the User's requested analysis. This data remains sandboxed within your browser and is not accessible to the Controller."
      ]},
      { type: "p", text: "This local storage is technically necessary for the functioning of the Service, is not used for tracking or advertising purposes, and remains sandboxed within the User's browser." },
      { type: "h3", text: "3.3. Voluntary Marketing Data" },
      { type: "p", text: "Only if you explicitly consent via a separate checkbox, we process your email address and limited activity metrics (such as daily usage streaks) to administer the optional Daily Bonus system and to send the Newsletter." },
      { type: "h2", text: "4. Third-Party Processors and Data Recipients" },
      { type: "ul", items: [
        "Infrastructure and Payments: We utilize Supabase (EU) for database hosting and authentication services, and Stripe (Global) for secure PCI-DSS compliant payment processing.",
        "Communications: We use Resend (USA) as our email delivery provider for sending transactional codes and, where consented, newsletters.",
        "Maps and Routing: To calculate distances and travel times, the Service transmits approximate location coordinates to routing and mapping services.",
        "Market Data & Valuations: Specific property location data may be cross-referenced with Public Market Data Sources to retrieve estimated market valuations.",
        "Contextual Events & Activities: To display nearby activities, the Service queries Contextual Event & Activity Providers. These providers receive general location coordinates and dates to return relevant events; no User identity or personal browsing history is shared with them.",
        "AI Processing: If the User voluntarily triggers the \"Virtual Staging\" feature, image URLs are transmitted transiently to AI Processing Providers solely for the generation of the requested content."
      ]},
      { type: "h2", text: "5. Legal Basis for Processing" },
      { type: "p", text: "In compliance with Article 6 of the GDPR, we process data based on the following grounds:" },
      { type: "ul", items: [
        "Performance of a Contract (Art. 6(1)(b)): For the core delivery of the analysis service, routing calculations, valuation estimates, account management, and processing payments.",
        "Legitimate Interest (Art. 6(1)(f)): For ensuring the security of the Extension, preventing fraud (e.g., credit abuse), and maintaining platform integrity.",
        "Explicit Consent (Art. 6(1)(a)): For optional features such as marketing communications, the Daily Bonus system, and AI-generated content.",
        "Legal Obligation (Art. 6(1)(c)): For tax reporting and accounting compliance."
      ]},
      { type: "h2", text: "6. User Rights" },
      { type: "p", text: "Under the GDPR, you have the right to access your data, rectify inaccuracies, erase your account (\"right to be forgotten\"), and object to processing based on legitimate interest. You also have the right to data portability (Art. 20) and the right to lodge a complaint with a supervisory authority (Art. 77), such as the Garante per la protezione dei dati personali." },
      { type: "p", text: "To exercise these rights, please contact: as.scirica@gmail.com." },
      { type: "h2", text: "7. Changes to this Policy" },
      { type: "p", text: "We may update this Privacy Policy from time to time. We will notify you of any significant changes via the Extension interface or email." },
    ],
  },
  it: {
    title: "Informativa sulla Privacy",
    lastUpdated: "Ultimo aggiornamento: 01 febbraio 2026",
    description: "Informativa sulla Privacy per l'estensione browser GetNearMe.",
    blocks: [
      { type: "h2", text: "1. Introduzione e Titolare del Trattamento" },
      { type: "p", text: "La presente Informativa sulla Privacy disciplina il trattamento dei dati personali in relazione all'utilizzo dell'estensione browser GetNearMe (il \"Servizio\"). La presente Informativa è volta a rispettare il Regolamento (UE) 2016/679 (GDPR) e la Direttiva 2002/58/CE (Direttiva ePrivacy) in materia di accesso e archiviazione delle informazioni sui dispositivi terminali degli utenti." },
      { type: "p", text: "Titolare del Trattamento: Antonio Scirica, operante commercialmente con il nome \"GetNearMe\"\nEmail: as.scirica@gmail.com" },
      { type: "h2", text: "2. Natura del Trattamento dei Dati" },
      { type: "p", text: "Per garantire la minimizzazione dei dati e il rigoroso rispetto dei diritti di proprietà intellettuale di terzi, il Servizio opera principalmente come utilità locale, lato client." },
      { type: "ul", items: [
        "Elaborazione Locale: L'analisi degli immobili viene eseguita dinamicamente all'interno del browser dell'Utente. Il Servizio non effettua indicizzazione o riproduzione di database di terze parti sui propri server per creare un motore di ricerca concorrente.",
        "Nessun Trasferimento Dati per Aggregazione: Il contenuto visibile sullo schermo dell'Utente viene elaborato temporaneamente nella memoria volatile del browser e non viene trasmesso ai server del Titolare per l'archiviazione permanente o l'aggregazione.",
        "I dati relativi agli immobili elaborati localmente dal Servizio si riferiscono principalmente a oggetti immobiliari e localizzazioni e non costituiscono tipicamente dati personali di persone fisiche identificabili ai sensi dell'Articolo 4 del GDPR."
      ]},
      { type: "h2", text: "3. Categorie di Dati Trattati" },
      { type: "p", text: "Trattiamo esclusivamente i dati strettamente necessari all'erogazione del Servizio, suddivisi per luogo di archiviazione:" },
      { type: "h3", text: "3.1. Dati Lato Server (Account e Log Tecnici)" },
      { type: "p", text: "La nostra infrastruttura backend elabora metadati limitati necessari per la gestione dell'account e la sicurezza:" },
      { type: "ul", items: [
        "Dati Identificativi: Indirizzo email e ID Utente (autenticato tramite Supabase) per la gestione dell'account e dell'abbonamento.",
        "Dati Transazionali: Stato dell'abbonamento, saldo crediti e identificativi di pagamento elaborati in modo sicuro da Stripe (non memorizziamo i numeri completi delle carte di credito).",
        "Log Tecnici del Servizio: Eventi di validazione tecnica che confermano la corretta esecuzione di un'operazione richiesta (utilizzati esclusivamente per la deduzione dei crediti e il debugging), senza memorizzare contenuti o attributi degli annunci.",
        "Sicurezza e Conservazione: Gli indirizzi IP e i log tecnici sono conservati solo per il periodo strettamente necessario a soddisfare il loro scopo specifico (monitoraggio della sicurezza, debugging e validazione del servizio) e vengono periodicamente cancellati in conformità con le politiche di conservazione interne per rispettare il principio di Limitazione della Conservazione (Art. 5(1)(e) GDPR)."
      ]},
      { type: "h3", text: "3.2. Dati Lato Client (Solo Dispositivo Locale)" },
      { type: "p", text: "Per visualizzare confronti e informazioni contestuali, il Servizio elabora i seguenti dati esclusivamente sul dispositivo dell'utente:" },
      { type: "ul", items: [
        "Dati di Sessione Temporanei: L'Estensione utilizza l'API Local Storage del browser (chrome.storage.local) per memorizzare temporaneamente nella cache dati fattuali limitati necessari per l'analisi visibile nella pagina richiesta dall'Utente. Questi dati rimangono isolati nel browser e non sono accessibili al Titolare."
      ]},
      { type: "p", text: "Questa archiviazione locale è tecnicamente necessaria per il funzionamento del Servizio, non viene utilizzata per finalità di tracciamento o pubblicitarie e rimane isolata all'interno del browser dell'Utente." },
      { type: "h3", text: "3.3. Dati di Marketing Volontari" },
      { type: "p", text: "Solo previo consenso esplicito tramite apposita casella, trattiamo il tuo indirizzo email e metriche di attività limitate (come le serie di utilizzo giornaliero) per amministrare il sistema opzionale Daily Bonus e per inviare la Newsletter." },
      { type: "h2", text: "4. Responsabili del Trattamento e Destinatari dei Dati" },
      { type: "ul", items: [
        "Infrastruttura e Pagamenti: Utilizziamo Supabase (UE) per l'hosting del database e i servizi di autenticazione, e Stripe (Globale) per l'elaborazione sicura dei pagamenti conforme PCI-DSS.",
        "Comunicazioni: Utilizziamo Resend (USA) come fornitore di servizi email per l'invio di codici transazionali e, previo consenso, newsletter.",
        "Mappe e Percorsi: Per calcolare distanze e tempi di percorrenza, il Servizio trasmette coordinate di posizione approssimative a servizi di routing e mappatura.",
        "Dati di Mercato e Valutazioni: Dati specifici sulla posizione dell'immobile possono essere incrociati con Fonti Pubbliche di Dati di Mercato per ottenere valutazioni di mercato stimate.",
        "Eventi e Attività Contestuali: Per mostrare attività nelle vicinanze, il Servizio interroga Fornitori di Eventi e Attività Contestuali. Questi fornitori ricevono coordinate di posizione generiche e date per restituire eventi pertinenti; nessuna identità dell'Utente o cronologia di navigazione viene condivisa con loro.",
        "Elaborazione AI: Se l'Utente attiva volontariamente la funzione \"Virtual Staging\", gli URL delle immagini vengono trasmessi temporaneamente a Fornitori di Elaborazione AI esclusivamente per la generazione del contenuto richiesto."
      ]},
      { type: "h2", text: "5. Base Giuridica del Trattamento" },
      { type: "p", text: "In conformità con l'Articolo 6 del GDPR, trattiamo i dati sulla base dei seguenti fondamenti:" },
      { type: "ul", items: [
        "Esecuzione di un Contratto (Art. 6(1)(b)): Per l'erogazione del servizio di analisi, calcoli di percorso, stime di valutazione, gestione dell'account ed elaborazione dei pagamenti.",
        "Interesse Legittimo (Art. 6(1)(f)): Per garantire la sicurezza dell'Estensione, prevenire frodi (es. abuso di crediti) e mantenere l'integrità della piattaforma.",
        "Consenso Esplicito (Art. 6(1)(a)): Per funzionalità opzionali come comunicazioni di marketing, il sistema Daily Bonus e contenuti generati dall'AI.",
        "Obbligo Legale (Art. 6(1)(c)): Per la dichiarazione fiscale e la conformità contabile."
      ]},
      { type: "h2", text: "6. Diritti dell'Utente" },
      { type: "p", text: "Ai sensi del GDPR, hai il diritto di accedere ai tuoi dati, rettificare inesattezze, cancellare il tuo account (\"diritto all'oblio\") e opporti al trattamento basato su interesse legittimo. Hai inoltre il diritto alla portabilità dei dati (Art. 20) e il diritto di proporre reclamo a un'autorità di controllo (Art. 77), come il Garante per la protezione dei dati personali." },
      { type: "p", text: "Per esercitare questi diritti, contattare: as.scirica@gmail.com." },
      { type: "h2", text: "7. Modifiche alla presente Informativa" },
      { type: "p", text: "Potremmo aggiornare la presente Informativa sulla Privacy di tanto in tanto. Ti informeremo di eventuali modifiche significative tramite l'interfaccia dell'Estensione o via email." },
    ],
  },
  es: {
    title: "Política de Privacidad",
    lastUpdated: "Última actualización: 01 de febrero de 2026",
    description: "Política de Privacidad para la extensión de navegador GetNearMe.",
    blocks: [
      { type: "h2", text: "1. Introducción y Responsable del Tratamiento" },
      { type: "p", text: "Esta Política de Privacidad regula el tratamiento de datos personales en relación con el uso de la extensión de navegador GetNearMe (el \"Servicio\"). Esta Política tiene como objetivo cumplir con el Reglamento (UE) 2016/679 (RGPD) y con la Directiva 2002/58/CE (Directiva ePrivacy) en materia de acceso y almacenamiento de información en los equipos terminales de los usuarios." },
      { type: "p", text: "Responsable del Tratamiento: Antonio Scirica, operando comercialmente bajo el nombre comercial \"GetNearMe\"\nEmail: as.scirica@gmail.com" },
      { type: "h2", text: "2. Naturaleza del Tratamiento de Datos" },
      { type: "p", text: "Para garantizar la minimización de datos y respetar estrictamente los derechos de propiedad intelectual de terceros, el Servicio opera principalmente como una utilidad local, del lado del cliente." },
      { type: "ul", items: [
        "Procesamiento Local: El análisis de propiedades inmobiliarias se realiza dinámicamente dentro del navegador del Usuario. El Servicio no realiza indexación ni reproducción de bases de datos de terceros en sus propios servidores para crear un motor de búsqueda competidor.",
        "Sin Transferencia de Datos para Agregación: El contenido visible en la pantalla del Usuario se procesa temporalmente en la memoria volátil del navegador y no se transmite a los servidores del Responsable para almacenamiento permanente o agregación.",
        "Los datos relacionados con propiedades procesados localmente por el Servicio se refieren principalmente a objetos inmobiliarios y ubicaciones y no constituyen típicamente datos personales de personas físicas identificables en el sentido del Artículo 4 del RGPD."
      ]},
      { type: "h2", text: "3. Categorías de Datos Tratados" },
      { type: "p", text: "Procesamos únicamente los datos estrictamente necesarios para prestar el Servicio, categorizados por ubicación de almacenamiento:" },
      { type: "h3", text: "3.1. Datos del Lado del Servidor (Cuenta y Registros Técnicos)" },
      { type: "p", text: "Nuestra infraestructura backend procesa metadatos limitados necesarios para la gestión de cuentas y seguridad:" },
      { type: "ul", items: [
        "Datos de Identidad: Dirección de correo electrónico e ID de Usuario (autenticado mediante Supabase) para gestionar su cuenta y suscripción.",
        "Datos Transaccionales: Estado de suscripción, saldo de créditos e identificadores de pago procesados de forma segura por Stripe (no almacenamos números completos de tarjetas de crédito).",
        "Registros Técnicos del Servicio: Eventos de validación técnica que confirman la ejecución exitosa de una operación solicitada (utilizados estrictamente para la deducción de créditos y depuración), sin almacenar contenido ni atributos de anuncios.",
        "Seguridad y Retención: Las direcciones IP y los registros técnicos se conservan únicamente durante el período estrictamente necesario para cumplir su propósito específico (monitoreo de seguridad, depuración y validación del servicio) y se eliminan periódicamente de acuerdo con las políticas de retención internas para cumplir con el principio de Limitación del Almacenamiento (Art. 5(1)(e) RGPD)."
      ]},
      { type: "h3", text: "3.2. Datos del Lado del Cliente (Solo Dispositivo Local)" },
      { type: "p", text: "Para mostrar comparaciones e información contextual, el Servicio procesa los siguientes datos exclusivamente en su dispositivo:" },
      { type: "ul", items: [
        "Datos de Sesión Temporales: La Extensión utiliza la API de almacenamiento local del navegador (chrome.storage.local) para almacenar temporalmente en caché datos factuales limitados necesarios para el análisis visible en la página requerida para el análisis solicitado por el Usuario. Estos datos permanecen aislados dentro de su navegador y no son accesibles para el Responsable."
      ]},
      { type: "p", text: "Este almacenamiento local es técnicamente necesario para el funcionamiento del Servicio, no se utiliza con fines de seguimiento o publicitarios y permanece aislado dentro del navegador del Usuario." },
      { type: "h3", text: "3.3. Datos de Marketing Voluntarios" },
      { type: "p", text: "Solo si usted consiente explícitamente mediante una casilla de verificación separada, procesamos su dirección de correo electrónico y métricas de actividad limitadas (como rachas de uso diario) para administrar el sistema opcional Daily Bonus y para enviar el Boletín." },
      { type: "h2", text: "4. Encargados del Tratamiento y Destinatarios de Datos" },
      { type: "ul", items: [
        "Infraestructura y Pagos: Utilizamos Supabase (UE) para el alojamiento de la base de datos y servicios de autenticación, y Stripe (Global) para el procesamiento seguro de pagos conforme a PCI-DSS.",
        "Comunicaciones: Utilizamos Resend (EE.UU.) como proveedor de envío de correo electrónico para códigos transaccionales y, cuando se consiente, boletines.",
        "Mapas y Rutas: Para calcular distancias y tiempos de viaje, el Servicio transmite coordenadas de ubicación aproximadas a servicios de enrutamiento y mapeo.",
        "Datos de Mercado y Valoraciones: Los datos de ubicación de propiedades específicas pueden cruzarse con Fuentes Públicas de Datos de Mercado para obtener valoraciones de mercado estimadas.",
        "Eventos y Actividades Contextuales: Para mostrar actividades cercanas, el Servicio consulta Proveedores de Eventos y Actividades Contextuales. Estos proveedores reciben coordenadas de ubicación generales y fechas para devolver eventos relevantes; no se comparte la identidad del Usuario ni el historial de navegación personal.",
        "Procesamiento de IA: Si el Usuario activa voluntariamente la función \"Virtual Staging\", las URLs de las imágenes se transmiten transitoriamente a Proveedores de Procesamiento de IA exclusivamente para la generación del contenido solicitado."
      ]},
      { type: "h2", text: "5. Base Jurídica del Tratamiento" },
      { type: "p", text: "En cumplimiento del Artículo 6 del RGPD, tratamos los datos en base a los siguientes fundamentos:" },
      { type: "ul", items: [
        "Ejecución de un Contrato (Art. 6(1)(b)): Para la prestación principal del servicio de análisis, cálculos de ruta, estimaciones de valoración, gestión de cuenta y procesamiento de pagos.",
        "Interés Legítimo (Art. 6(1)(f)): Para garantizar la seguridad de la Extensión, prevenir fraudes (ej. abuso de créditos) y mantener la integridad de la plataforma.",
        "Consentimiento Explícito (Art. 6(1)(a)): Para funciones opcionales como comunicaciones de marketing, el sistema Daily Bonus y contenido generado por IA.",
        "Obligación Legal (Art. 6(1)(c)): Para la declaración de impuestos y el cumplimiento contable."
      ]},
      { type: "h2", text: "6. Derechos del Usuario" },
      { type: "p", text: "Bajo el RGPD, usted tiene derecho a acceder a sus datos, rectificar inexactitudes, eliminar su cuenta (\"derecho al olvido\") y oponerse al tratamiento basado en interés legítimo. También tiene derecho a la portabilidad de datos (Art. 20) y a presentar una reclamación ante una autoridad de control (Art. 77), como el Garante per la protezione dei dati personali." },
      { type: "p", text: "Para ejercer estos derechos, contacte: as.scirica@gmail.com." },
      { type: "h2", text: "7. Cambios en esta Política" },
      { type: "p", text: "Podemos actualizar esta Política de Privacidad periódicamente. Le notificaremos cualquier cambio significativo a través de la interfaz de la Extensión o por correo electrónico." },
    ],
  },
  fr: {
    title: "Politique de Confidentialité",
    lastUpdated: "Dernière mise à jour : 01 février 2026",
    description: "Politique de Confidentialité pour l'extension de navigateur GetNearMe.",
    blocks: [
      { type: "h2", text: "1. Introduction et Responsable du Traitement" },
      { type: "p", text: "La présente Politique de Confidentialité régit le traitement des données personnelles dans le cadre de l'utilisation de l'extension de navigateur GetNearMe (le \"Service\"). Cette Politique vise à respecter le Règlement (UE) 2016/679 (RGPD) et la Directive 2002/58/CE (Directive ePrivacy) concernant l'accès et le stockage d'informations sur les équipements terminaux des utilisateurs." },
      { type: "p", text: "Responsable du Traitement : Antonio Scirica, opérant commercialement sous le nom commercial \"GetNearMe\"\nEmail : as.scirica@gmail.com" },
      { type: "h2", text: "2. Nature du Traitement des Données" },
      { type: "p", text: "Pour garantir la minimisation des données et respecter strictement les droits de propriété intellectuelle des tiers, le Service fonctionne principalement comme un utilitaire local, côté client." },
      { type: "ul", items: [
        "Traitement Local : L'analyse des biens immobiliers est effectuée dynamiquement dans le navigateur de l'Utilisateur. Le Service ne pratique pas l'indexation ou la reproduction de bases de données tierces sur ses propres serveurs pour créer un moteur de recherche concurrent.",
        "Pas de Transfert de Données pour l'Agrégation : Le contenu visible sur l'écran de l'Utilisateur est traité temporairement dans la mémoire volatile du navigateur et n'est pas transmis aux serveurs du Responsable pour un stockage permanent ou une agrégation.",
        "Les données relatives aux biens immobiliers traitées localement par le Service se rapportent principalement à des objets immobiliers et des emplacements et ne constituent généralement pas des données personnelles de personnes physiques identifiables au sens de l'Article 4 du RGPD."
      ]},
      { type: "h2", text: "3. Catégories de Données Traitées" },
      { type: "p", text: "Nous ne traitons que les données strictement nécessaires à la fourniture du Service, classées par lieu de stockage :" },
      { type: "h3", text: "3.1. Données Côté Serveur (Compte et Journaux Techniques)" },
      { type: "p", text: "Notre infrastructure backend traite des métadonnées limitées nécessaires à la gestion des comptes et à la sécurité :" },
      { type: "ul", items: [
        "Données d'Identité : Adresse e-mail et identifiant utilisateur (authentifié via Supabase) pour gérer votre compte et abonnement.",
        "Données Transactionnelles : Statut de l'abonnement, solde de crédits et identifiants de paiement traités de manière sécurisée par Stripe (nous ne stockons pas les numéros complets de cartes de crédit).",
        "Journaux Techniques du Service : Événements de validation technique confirmant l'exécution réussie d'une opération demandée (utilisés strictement pour la déduction de crédits et le débogage), sans stocker le contenu ou les attributs des annonces.",
        "Sécurité et Conservation : Les adresses IP et les journaux techniques ne sont conservés que pendant la durée strictement nécessaire à l'accomplissement de leur finalité spécifique (surveillance de la sécurité, débogage et validation du service) et sont périodiquement supprimés conformément aux politiques de conservation internes pour respecter le principe de Limitation de la Conservation (Art. 5(1)(e) RGPD)."
      ]},
      { type: "h3", text: "3.2. Données Côté Client (Appareil Local Uniquement)" },
      { type: "p", text: "Pour afficher des comparaisons et des informations contextuelles, le Service traite les données suivantes exclusivement sur votre appareil :" },
      { type: "ul", items: [
        "Données de Session Temporaires : L'Extension utilise l'API de stockage local du navigateur (chrome.storage.local) pour mettre temporairement en cache des données factuelles limitées nécessaires à l'analyse visible sur la page requise pour l'analyse demandée par l'Utilisateur. Ces données restent isolées dans votre navigateur et ne sont pas accessibles au Responsable."
      ]},
      { type: "p", text: "Ce stockage local est techniquement nécessaire au fonctionnement du Service, n'est pas utilisé à des fins de suivi ou publicitaires et reste isolé dans le navigateur de l'Utilisateur." },
      { type: "h3", text: "3.3. Données Marketing Volontaires" },
      { type: "p", text: "Uniquement si vous consentez explicitement via une case à cocher séparée, nous traitons votre adresse e-mail et vos métriques d'activité limitées (telles que les séries d'utilisation quotidienne) pour administrer le système optionnel Daily Bonus et pour envoyer la Newsletter." },
      { type: "h2", text: "4. Sous-traitants et Destinataires des Données" },
      { type: "ul", items: [
        "Infrastructure et Paiements : Nous utilisons Supabase (UE) pour l'hébergement de la base de données et les services d'authentification, et Stripe (Global) pour le traitement sécurisé des paiements conforme PCI-DSS.",
        "Communications : Nous utilisons Resend (USA) comme fournisseur de livraison d'e-mails pour l'envoi de codes transactionnels et, sous réserve de consentement, de newsletters.",
        "Cartes et Itinéraires : Pour calculer les distances et les temps de trajet, le Service transmet des coordonnées de localisation approximatives à des services de routage et de cartographie.",
        "Données de Marché et Évaluations : Les données de localisation de propriétés spécifiques peuvent être croisées avec des Sources Publiques de Données de Marché pour obtenir des évaluations de marché estimées.",
        "Événements et Activités Contextuels : Pour afficher les activités à proximité, le Service interroge des Fournisseurs d'Événements et d'Activités Contextuels. Ces fournisseurs reçoivent des coordonnées de localisation générales et des dates pour renvoyer des événements pertinents ; aucune identité de l'Utilisateur ni historique de navigation personnel n'est partagé avec eux.",
        "Traitement par IA : Si l'Utilisateur déclenche volontairement la fonctionnalité \"Virtual Staging\", les URLs des images sont transmises de manière transitoire à des Fournisseurs de Traitement par IA uniquement pour la génération du contenu demandé."
      ]},
      { type: "h2", text: "5. Base Juridique du Traitement" },
      { type: "p", text: "En conformité avec l'Article 6 du RGPD, nous traitons les données sur les bases suivantes :" },
      { type: "ul", items: [
        "Exécution d'un Contrat (Art. 6(1)(b)) : Pour la fourniture principale du service d'analyse, les calculs d'itinéraire, les estimations d'évaluation, la gestion de compte et le traitement des paiements.",
        "Intérêt Légitime (Art. 6(1)(f)) : Pour assurer la sécurité de l'Extension, prévenir la fraude (ex. abus de crédits) et maintenir l'intégrité de la plateforme.",
        "Consentement Explicite (Art. 6(1)(a)) : Pour les fonctionnalités optionnelles telles que les communications marketing, le système Daily Bonus et le contenu généré par l'IA.",
        "Obligation Légale (Art. 6(1)(c)) : Pour la déclaration fiscale et la conformité comptable."
      ]},
      { type: "h2", text: "6. Droits de l'Utilisateur" },
      { type: "p", text: "En vertu du RGPD, vous avez le droit d'accéder à vos données, de rectifier les inexactitudes, d'effacer votre compte (\"droit à l'oubli\") et de vous opposer au traitement fondé sur l'intérêt légitime. Vous avez également le droit à la portabilité des données (Art. 20) et le droit de déposer une plainte auprès d'une autorité de contrôle (Art. 77), telle que le Garante per la protezione dei dati personali." },
      { type: "p", text: "Pour exercer ces droits, contactez : as.scirica@gmail.com." },
      { type: "h2", text: "7. Modifications de cette Politique" },
      { type: "p", text: "Nous pouvons mettre à jour cette Politique de Confidentialité de temps à autre. Nous vous informerons de tout changement significatif via l'interface de l'Extension ou par e-mail." },
    ],
  },
  ru: {
    title: "Политика конфиденциальности",
    lastUpdated: "Последнее обновление: 01 февраля 2026",
    description: "Политика конфиденциальности расширения браузера GetNearMe.",
    blocks: [
      { type: "h2", text: "1. Введение и Контролёр данных" },
      { type: "p", text: "Настоящая Политика конфиденциальности регулирует обработку персональных данных в связи с использованием расширения браузера GetNearMe (\"Сервис\"). Настоящая Политика направлена на соблюдение Регламента (ЕС) 2016/679 (GDPR) и Директивы 2002/58/EC (Директива ePrivacy) в отношении доступа к информации и её хранения на терминальном оборудовании пользователей." },
      { type: "p", text: "Контролёр данных: Антонио Шрика, действующий коммерчески под торговым наименованием \"GetNearMe\"\nEmail: as.scirica@gmail.com" },
      { type: "h2", text: "2. Характер обработки данных" },
      { type: "p", text: "Для обеспечения минимизации данных и строгого соблюдения прав интеллектуальной собственности третьих лиц Сервис функционирует преимущественно как локальная, клиентская утилита." },
      { type: "ul", items: [
        "Локальная обработка: Анализ объектов недвижимости выполняется динамически в браузере Пользователя. Сервис не осуществляет индексацию или воспроизведение баз данных третьих лиц на своих серверах для создания конкурирующей поисковой системы.",
        "Отсутствие передачи данных для агрегации: Контент, видимый на экране Пользователя, обрабатывается временно в оперативной памяти браузера и не передаётся на серверы Контролёра для постоянного хранения или агрегации.",
        "Данные, связанные с недвижимостью, обрабатываемые локально Сервисом, относятся преимущественно к объектам недвижимости и местоположениям и, как правило, не являются персональными данными идентифицируемых физических лиц по смыслу Статьи 4 GDPR."
      ]},
      { type: "h2", text: "3. Категории обрабатываемых данных" },
      { type: "p", text: "Мы обрабатываем только данные, строго необходимые для предоставления Сервиса, классифицированные по месту хранения:" },
      { type: "h3", text: "3.1. Серверные данные (Аккаунт и технические журналы)" },
      { type: "p", text: "Наша серверная инфраструктура обрабатывает ограниченные метаданные, необходимые для управления аккаунтом и обеспечения безопасности:" },
      { type: "ul", items: [
        "Идентификационные данные: Адрес электронной почты и ID пользователя (аутентификация через Supabase) для управления аккаунтом и подпиской.",
        "Транзакционные данные: Статус подписки, баланс кредитов и идентификаторы платежей, безопасно обрабатываемые Stripe (мы не храним полные номера кредитных карт).",
        "Технические журналы сервиса: События технической валидации, подтверждающие успешное выполнение запрошенной операции (используются исключительно для списания кредитов и отладки), без хранения содержания или атрибутов объявлений.",
        "Безопасность и хранение: IP-адреса и технические журналы хранятся только в течение периода, строго необходимого для выполнения их конкретной цели (мониторинг безопасности, отладка и валидация сервиса) и периодически удаляются в соответствии с внутренними политиками хранения для соблюдения принципа ограничения хранения (Ст. 5(1)(e) GDPR)."
      ]},
      { type: "h3", text: "3.2. Клиентские данные (только локальное устройство)" },
      { type: "p", text: "Для отображения сравнений и контекстной информации Сервис обрабатывает следующие данные исключительно на вашем устройстве:" },
      { type: "ul", items: [
        "Временные данные сессии: Расширение использует API локального хранилища браузера (chrome.storage.local) для временного кэширования ограниченных фактических данных, необходимых для анализа, видимого на странице для запрошенного Пользователем анализа. Эти данные остаются изолированными в вашем браузере и недоступны Контролёру."
      ]},
      { type: "p", text: "Данное локальное хранилище является технически необходимым для функционирования Сервиса, не используется в целях отслеживания или рекламы и остаётся изолированным в браузере Пользователя." },
      { type: "h3", text: "3.3. Добровольные маркетинговые данные" },
      { type: "p", text: "Только при вашем явном согласии через отдельный флажок мы обрабатываем ваш адрес электронной почты и ограниченные метрики активности (такие как ежедневные серии использования) для администрирования опциональной системы Daily Bonus и для отправки Рассылки." },
      { type: "h2", text: "4. Обработчики данных и получатели" },
      { type: "ul", items: [
        "Инфраструктура и платежи: Мы используем Supabase (ЕС) для хостинга баз данных и услуг аутентификации, а также Stripe (Глобально) для безопасной обработки платежей, соответствующей PCI-DSS.",
        "Коммуникации: Мы используем Resend (США) в качестве провайдера доставки электронной почты для отправки транзакционных кодов и, при наличии согласия, рассылок.",
        "Карты и маршруты: Для расчёта расстояний и времени в пути Сервис передаёт приблизительные координаты местоположения сервисам маршрутизации и картографии.",
        "Рыночные данные и оценки: Конкретные данные о местоположении недвижимости могут быть сопоставлены с Публичными источниками рыночных данных для получения ориентировочных рыночных оценок.",
        "Контекстные события и мероприятия: Для отображения ближайших мероприятий Сервис обращается к Провайдерам контекстных событий и мероприятий. Эти провайдеры получают общие координаты местоположения и даты для возврата релевантных событий; личность Пользователя или история просмотров не передаются им.",
        "Обработка ИИ: Если Пользователь добровольно активирует функцию \"Virtual Staging\", URL-адреса изображений временно передаются Провайдерам обработки ИИ исключительно для генерации запрошенного контента."
      ]},
      { type: "h2", text: "5. Правовая основа обработки" },
      { type: "p", text: "В соответствии со Статьёй 6 GDPR мы обрабатываем данные на следующих основаниях:" },
      { type: "ul", items: [
        "Исполнение договора (Ст. 6(1)(b)): Для основного предоставления аналитического сервиса, расчётов маршрутов, оценочных расчётов, управления аккаунтом и обработки платежей.",
        "Законный интерес (Ст. 6(1)(f)): Для обеспечения безопасности Расширения, предотвращения мошенничества (напр., злоупотребление кредитами) и поддержания целостности платформы.",
        "Явное согласие (Ст. 6(1)(a)): Для опциональных функций, таких как маркетинговые коммуникации, система Daily Bonus и контент, сгенерированный ИИ.",
        "Юридическая обязанность (Ст. 6(1)(c)): Для налоговой отчётности и бухгалтерского соответствия."
      ]},
      { type: "h2", text: "6. Права пользователя" },
      { type: "p", text: "Согласно GDPR, вы имеете право на доступ к своим данным, исправление неточностей, удаление аккаунта (\"право на забвение\") и возражение против обработки на основании законного интереса. Вы также имеете право на переносимость данных (Ст. 20) и право подать жалобу в надзорный орган (Ст. 77), такой как Garante per la protezione dei dati personali." },
      { type: "p", text: "Для осуществления этих прав обращайтесь: as.scirica@gmail.com." },
      { type: "h2", text: "7. Изменения настоящей Политики" },
      { type: "p", text: "Мы можем периодически обновлять настоящую Политику конфиденциальности. Мы уведомим вас о любых существенных изменениях через интерфейс Расширения или по электронной почте." },
    ],
  },
  uk: {
    title: "Політика конфіденційності",
    lastUpdated: "Останнє оновлення: 01 лютого 2026",
    description: "Політика конфіденційності розширення браузера GetNearMe.",
    blocks: [
      { type: "h2", text: "1. Вступ та Контролер даних" },
      { type: "p", text: "Ця Політика конфіденційності регулює обробку персональних даних у зв'язку з використанням розширення браузера GetNearMe (\"Сервіс\"). Ця Політика спрямована на дотримання Регламенту (ЄС) 2016/679 (GDPR) та Директиви 2002/58/EC (Директива ePrivacy) щодо доступу до інформації та її зберігання на термінальному обладнанні користувачів." },
      { type: "p", text: "Контролер даних: Антоніо Шріка, що діє комерційно під торговою назвою \"GetNearMe\"\nEmail: as.scirica@gmail.com" },
      { type: "h2", text: "2. Характер обробки даних" },
      { type: "p", text: "Для забезпечення мінімізації даних та суворого дотримання прав інтелектуальної власності третіх осіб Сервіс функціонує переважно як локальна, клієнтська утиліта." },
      { type: "ul", items: [
        "Локальна обробка: Аналіз об'єктів нерухомості виконується динамічно у браузері Користувача. Сервіс не здійснює індексацію або відтворення баз даних третіх осіб на своїх серверах для створення конкуруючої пошукової системи.",
        "Відсутність передачі даних для агрегації: Контент, видимий на екрані Користувача, обробляється тимчасово в оперативній пам'яті браузера і не передається на сервери Контролера для постійного зберігання або агрегації.",
        "Дані, пов'язані з нерухомістю, що обробляються локально Сервісом, переважно стосуються об'єктів нерухомості та місцеположень і, як правило, не є персональними даними ідентифікованих фізичних осіб у розумінні Статті 4 GDPR."
      ]},
      { type: "h2", text: "3. Категорії оброблюваних даних" },
      { type: "p", text: "Ми обробляємо лише дані, суворо необхідні для надання Сервісу, класифіковані за місцем зберігання:" },
      { type: "h3", text: "3.1. Серверні дані (Акаунт та технічні журнали)" },
      { type: "p", text: "Наша серверна інфраструктура обробляє обмежені метадані, необхідні для управління акаунтом та забезпечення безпеки:" },
      { type: "ul", items: [
        "Ідентифікаційні дані: Адреса електронної пошти та ID користувача (автентифікація через Supabase) для управління акаунтом та підпискою.",
        "Транзакційні дані: Статус підписки, баланс кредитів та ідентифікатори платежів, безпечно оброблювані Stripe (ми не зберігаємо повні номери кредитних карток).",
        "Технічні журнали сервісу: Події технічної валідації, що підтверджують успішне виконання запитаної операції (використовуються виключно для списання кредитів та налагодження), без зберігання вмісту або атрибутів оголошень.",
        "Безпека та зберігання: IP-адреси та технічні журнали зберігаються лише протягом періоду, суворо необхідного для виконання їх конкретної мети (моніторинг безпеки, налагодження та валідація сервісу) та періодично видаляються відповідно до внутрішніх політик зберігання для дотримання принципу обмеження зберігання (Ст. 5(1)(e) GDPR)."
      ]},
      { type: "h3", text: "3.2. Клієнтські дані (лише локальний пристрій)" },
      { type: "p", text: "Для відображення порівнянь та контекстної інформації Сервіс обробляє наступні дані виключно на вашому пристрої:" },
      { type: "ul", items: [
        "Тимчасові дані сесії: Розширення використовує API локального сховища браузера (chrome.storage.local) для тимчасового кешування обмежених фактичних даних, необхідних для аналізу, видимого на сторінці для запитаного Користувачем аналізу. Ці дані залишаються ізольованими у вашому браузері та недоступні Контролеру."
      ]},
      { type: "p", text: "Це локальне сховище є технічно необхідним для функціонування Сервісу, не використовується з метою відстеження або реклами та залишається ізольованим у браузері Користувача." },
      { type: "h3", text: "3.3. Добровільні маркетингові дані" },
      { type: "p", text: "Лише за вашої явної згоди через окремий прапорець ми обробляємо вашу адресу електронної пошти та обмежені метрики активності (такі як щоденні серії використання) для адміністрування опціональної системи Daily Bonus та для відправки Розсилки." },
      { type: "h2", text: "4. Обробники даних та отримувачі" },
      { type: "ul", items: [
        "Інфраструктура та платежі: Ми використовуємо Supabase (ЄС) для хостингу баз даних та послуг автентифікації, а також Stripe (Глобально) для безпечної обробки платежів, відповідної PCI-DSS.",
        "Комунікації: Ми використовуємо Resend (США) як провайдера доставки електронної пошти для відправки транзакційних кодів та, за наявності згоди, розсилок.",
        "Карти та маршрути: Для розрахунку відстаней та часу подорожі Сервіс передає приблизні координати місцеположення сервісам маршрутизації та картографії.",
        "Ринкові дані та оцінки: Конкретні дані про місцеположення нерухомості можуть бути зіставлені з Публічними джерелами ринкових даних для отримання орієнтовних ринкових оцінок.",
        "Контекстні події та заходи: Для відображення найближчих заходів Сервіс звертається до Провайдерів контекстних подій та заходів. Ці провайдери отримують загальні координати місцеположення та дати для повернення релевантних подій; особистість Користувача або історія перегляду не передаються їм.",
        "Обробка ШІ: Якщо Користувач добровільно активує функцію \"Virtual Staging\", URL-адреси зображень тимчасово передаються Провайдерам обробки ШІ виключно для генерації запитаного контенту."
      ]},
      { type: "h2", text: "5. Правова основа обробки" },
      { type: "p", text: "Відповідно до Статті 6 GDPR ми обробляємо дані на таких підставах:" },
      { type: "ul", items: [
        "Виконання договору (Ст. 6(1)(b)): Для основного надання аналітичного сервісу, розрахунків маршрутів, оціночних розрахунків, управління акаунтом та обробки платежів.",
        "Законний інтерес (Ст. 6(1)(f)): Для забезпечення безпеки Розширення, запобігання шахрайству (напр., зловживання кредитами) та підтримання цілісності платформи.",
        "Явна згода (Ст. 6(1)(a)): Для опціональних функцій, таких як маркетингові комунікації, система Daily Bonus та контент, згенерований ШІ.",
        "Юридичний обов'язок (Ст. 6(1)(c)): Для податкової звітності та бухгалтерської відповідності."
      ]},
      { type: "h2", text: "6. Права користувача" },
      { type: "p", text: "Згідно з GDPR, ви маєте право на доступ до своїх даних, виправлення неточностей, видалення акаунту (\"право на забуття\") та заперечення проти обробки на підставі законного інтересу. Ви також маєте право на переносимість даних (Ст. 20) та право подати скаргу до наглядового органу (Ст. 77), такого як Garante per la protezione dei dati personali." },
      { type: "p", text: "Для здійснення цих прав звертайтеся: as.scirica@gmail.com." },
      { type: "h2", text: "7. Зміни цієї Політики" },
      { type: "p", text: "Ми можемо періодично оновлювати цю Політику конфіденційності. Ми повідомимо вас про будь-які суттєві зміни через інтерфейс Розширення або електронною поштою." },
    ],
  },
};

export const termsContent: Record<Locale, LegalPage> = {
  en: {
    title: "Terms of Service",
    lastUpdated: "Last Updated: 01 February 2026",
    description: "Terms of Service for the GetNearMe browser extension.",
    blocks: [
      { type: "h2", text: "1. Acceptance of Terms" },
      { type: "p", text: "By installing or using the GetNearMe extension (\"Service\"), you agree to be bound by these Terms of Service (\"Terms\"). You affirm that you are at least 18 years of age and are fully able and competent to enter into this agreement. If you do not agree, you must immediately uninstall the Service." },
      { type: "h2", text: "2. License and Nature of Service" },
      { type: "p", text: "2.1. Client-Side Utility: You acknowledge that the Service operates as a \"User Agent\" or browser utility under your direct control. It is designed to augment your local browsing experience by visualizing independent market insights." },
      { type: "p", text: "2.2. Limited License: We grant you a revocable, non-exclusive, non-transferable license to use the Service solely for your personal or internal business analysis of real estate market data." },
      { type: "h2", text: "3. Restrictions and Intellectual Property" },
      { type: "p", text: "3.1. Independence: GetNearMe is an independent software tool. We are not affiliated with, endorsed by, sponsored by, or officially connected to any real estate platform (such as Immobiliare.it, Idealista, or others). All third-party trademarks are the property of their respective owners and are used solely for descriptive compatibility purposes (Nominative Fair Use)." },
      { type: "p", text: "3.2. Prohibited Conduct: You explicitly agree NOT to use the Service to:" },
      { type: "ul", items: [
        "Perform mass extraction of data for the purpose of creating a competing database, search engine, or commercial service.",
        "Bypass any security measures, CAPTCHAs, or authentication barriers of third-party platforms.",
        "Violate the Terms of Service of any third-party real estate portal visited while using the Extension.",
        "Attempt to bypass, disable, or defeat any technical restrictions or content protection measures implemented within the Service (including restrictions on printing, copying, or exporting data)."
      ]},
      { type: "h2", text: "4. Disclaimers and Limitations of Liability" },
      { type: "p", text: "4.1. Estimated Values: Any \"Estimated Total\" or financial calculation provided by the Service represents an indicative estimate of costs associated with a property purchase (e.g., agency fees, notary costs, taxes). These estimates are for informational purposes only and do not constitute a binding offer or professional financial quote." },
      { type: "p", text: "4.2. Data Reliability: The information visualized by the Service is derived from publicly available data, information present in the analyzed listings, and automatic processing. We do not verify energy classes via official certificates (APE) nor guarantee the accuracy of data in the source listings. Inaccuracies or omissions in the original third-party listing may be reflected in the Service's report." },
      { type: "p", text: "4.3. No Professional Advice: The Service does not substitute technical, legal, fiscal, or real estate verification performed by qualified professionals. To the extent permitted by applicable law, GetNearMe assumes no responsibility for decisions made based on the information provided." },
      { type: "h2", text: "5. Credits, Payments, and Refunds" },
      { type: "p", text: "5.1. Purchase of Credits: The Service operates on a credit-based system. Credits are virtual units used solely to unlock specific features or analyses within the Extension. Credits do not represent prepaid funds, electronic money, or stored value, have no monetary value outside the Service, and cannot be exchanged for cash, refunded, or transferred to other accounts." },
      { type: "p", text: "5.2. Payment Processing: All payments are processed securely and exclusively by Stripe in accordance with its own terms and privacy policies. GetNearMe does not store or have access to users' full payment card details. By purchasing credits, you authorize Stripe to charge your selected payment method for the applicable amount." },
      { type: "p", text: "5.3. Waiver of Right of Withdrawal: By purchasing digital credits, you expressly consent to the immediate performance of the contract and expressly acknowledge that, once the credits are credited to your account, you lose your right of withdrawal (cooling-off period) in accordance with Article 16(m) of Directive 2011/83/EU on Consumer Rights." },
      { type: "p", text: "5.4. Refund Policy: All purchases of credits are final and non-refundable, except where mandatory consumer protection laws provide otherwise. No refunds will be issued for unused credits or if you choose to stop using the Service." },
      { type: "p", text: "In the event of a proven technical error attributable solely to GetNearMe (for example, credits paid for but not credited to the user's account), the user may contact support at as.scirica@gmail.com for verification and rectification." },
      { type: "h2", text: "6. Liability" },
      { type: "p", text: "To the maximum extent permitted by applicable law, GetNearMe shall not be liable for any indirect, incidental, special, or consequential damages, including loss of profits, data, use, or goodwill, arising out of or in connection with your use of, or inability to use, the Service." },
      { type: "p", text: "The Service is provided for informational and illustrative purposes only and relies on publicly available information, third-party platforms, and automated processing. GetNearMe does not guarantee the accuracy, completeness, or availability of any information, estimates, or AI-generated outputs and is not responsible for decisions or actions taken based on the Service." },
      { type: "p", text: "These limitations apply only to the extent permitted by applicable law." },
      { type: "h2", text: "7. Termination" },
      { type: "p", text: "We reserve the right to suspend or terminate your access to the Service immediately, without prior notice, if you breach these Terms, particularly regarding the unauthorized mass extraction of data or violation of third-party rights." },
      { type: "h2", text: "8. General Provisions" },
      { type: "p", text: "8.1. Severability: If any provision of these Terms is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that these Terms will otherwise remain in full force and effect." },
      { type: "p", text: "8.2. Changes to Terms: We reserve the right to modify these Terms at any time at our sole discretion. Continued use of the Service following any changes constitutes your acceptance of the new Terms." },
      { type: "h2", text: "9. Governing Law and Jurisdiction" },
      { type: "p", text: "These Terms shall be governed by the laws of Italy. Any dispute arising out of or relating to these Terms shall be subject to the exclusive jurisdiction of the competent courts of Rome, Italy. European consumers have the right to use the Online Dispute Resolution platform." },
    ],
  },
  it: {
    title: "Termini di Servizio",
    lastUpdated: "Ultimo aggiornamento: 01 febbraio 2026",
    description: "Termini di Servizio per l'estensione browser GetNearMe.",
    blocks: [
      { type: "h2", text: "1. Accettazione dei Termini" },
      { type: "p", text: "Installando o utilizzando l'estensione GetNearMe (\"Servizio\"), l'utente accetta di essere vincolato dai presenti Termini di Servizio (\"Termini\"). L'utente dichiara di avere almeno 18 anni e di essere pienamente capace e competente per stipulare il presente accordo. In caso di disaccordo, l'utente deve immediatamente disinstallare il Servizio." },
      { type: "h2", text: "2. Licenza e Natura del Servizio" },
      { type: "p", text: "2.1. Utilità Lato Client: L'utente riconosce che il Servizio opera come \"User Agent\" o utilità del browser sotto il suo diretto controllo. È progettato per migliorare l'esperienza di navigazione locale visualizzando approfondimenti di mercato indipendenti." },
      { type: "p", text: "2.2. Licenza Limitata: Concediamo una licenza revocabile, non esclusiva e non trasferibile per utilizzare il Servizio esclusivamente per l'analisi personale o aziendale interna di dati del mercato immobiliare." },
      { type: "h2", text: "3. Restrizioni e Proprietà Intellettuale" },
      { type: "p", text: "3.1. Indipendenza: GetNearMe è uno strumento software indipendente. Non siamo affiliati, approvati, sponsorizzati o ufficialmente collegati ad alcuna piattaforma immobiliare (come Immobiliare.it, Idealista o altre). Tutti i marchi di terze parti sono di proprietà dei rispettivi titolari e sono utilizzati esclusivamente a fini descrittivi di compatibilità (Nominative Fair Use)." },
      { type: "p", text: "3.2. Condotta Vietata: L'utente si impegna esplicitamente a NON utilizzare il Servizio per:" },
      { type: "ul", items: [
        "Effettuare estrazione massiva di dati allo scopo di creare un database concorrente, un motore di ricerca o un servizio commerciale.",
        "Aggirare misure di sicurezza, CAPTCHA o barriere di autenticazione di piattaforme di terze parti.",
        "Violare i Termini di Servizio di qualsiasi portale immobiliare di terze parti visitato durante l'utilizzo dell'Estensione.",
        "Tentare di aggirare, disabilitare o sconfiggere qualsiasi restrizione tecnica o misura di protezione dei contenuti implementata nel Servizio (incluse le restrizioni su stampa, copia o esportazione dei dati)."
      ]},
      { type: "h2", text: "4. Esclusioni e Limitazioni di Responsabilità" },
      { type: "p", text: "4.1. Valori Stimati: Qualsiasi \"Totale Stimato\" o calcolo finanziario fornito dal Servizio rappresenta una stima indicativa dei costi associati all'acquisto di un immobile (es. commissioni di agenzia, costi notarili, imposte). Queste stime hanno scopo puramente informativo e non costituiscono un'offerta vincolante o una quotazione finanziaria professionale." },
      { type: "p", text: "4.2. Affidabilità dei Dati: Le informazioni visualizzate dal Servizio derivano da dati pubblicamente disponibili, informazioni presenti negli annunci analizzati ed elaborazione automatica. Non verifichiamo le classi energetiche tramite certificati ufficiali (APE) né garantiamo l'accuratezza dei dati negli annunci di origine. Inesattezze o omissioni nell'annuncio originale di terze parti possono riflettersi nel report del Servizio." },
      { type: "p", text: "4.3. Nessuna Consulenza Professionale: Il Servizio non sostituisce la verifica tecnica, legale, fiscale o immobiliare svolta da professionisti qualificati. Nei limiti consentiti dalla legge applicabile, GetNearMe non assume alcuna responsabilità per le decisioni prese sulla base delle informazioni fornite." },
      { type: "h2", text: "5. Crediti, Pagamenti e Rimborsi" },
      { type: "p", text: "5.1. Acquisto di Crediti: Il Servizio opera su un sistema basato su crediti. I crediti sono unità virtuali utilizzate esclusivamente per sbloccare funzionalità o analisi specifiche all'interno dell'Estensione. I crediti non rappresentano fondi prepagati, moneta elettronica o valore conservato, non hanno valore monetario al di fuori del Servizio e non possono essere scambiati in denaro, rimborsati o trasferiti ad altri account." },
      { type: "p", text: "5.2. Elaborazione dei Pagamenti: Tutti i pagamenti sono elaborati in modo sicuro ed esclusivamente da Stripe in conformità con i propri termini e politiche sulla privacy. GetNearMe non memorizza né ha accesso ai dati completi delle carte di pagamento degli utenti. Acquistando crediti, l'utente autorizza Stripe ad addebitare il metodo di pagamento selezionato per l'importo applicabile." },
      { type: "p", text: "5.3. Rinuncia al Diritto di Recesso: Acquistando crediti digitali, l'utente acconsente espressamente all'esecuzione immediata del contratto e riconosce espressamente che, una volta accreditati i crediti sul proprio account, perde il diritto di recesso (periodo di ripensamento) ai sensi dell'Articolo 16(m) della Direttiva 2011/83/UE sui Diritti dei Consumatori." },
      { type: "p", text: "5.4. Politica di Rimborso: Tutti gli acquisti di crediti sono definitivi e non rimborsabili, salvo diversa disposizione delle leggi obbligatorie a tutela dei consumatori. Non verranno emessi rimborsi per crediti non utilizzati o in caso di cessazione dell'uso del Servizio." },
      { type: "p", text: "In caso di errore tecnico comprovato attribuibile esclusivamente a GetNearMe (ad esempio, crediti pagati ma non accreditati sull'account dell'utente), l'utente può contattare il supporto all'indirizzo as.scirica@gmail.com per la verifica e la rettifica." },
      { type: "h2", text: "6. Responsabilità" },
      { type: "p", text: "Nei limiti massimi consentiti dalla legge applicabile, GetNearMe non sarà responsabile per danni indiretti, incidentali, speciali o consequenziali, inclusa la perdita di profitti, dati, utilizzo o avviamento, derivanti dall'uso o dall'impossibilità di utilizzare il Servizio." },
      { type: "p", text: "Il Servizio è fornito esclusivamente a scopo informativo e illustrativo e si basa su informazioni pubblicamente disponibili, piattaforme di terze parti ed elaborazione automatizzata. GetNearMe non garantisce l'accuratezza, la completezza o la disponibilità di qualsiasi informazione, stima o output generato dall'IA e non è responsabile per decisioni o azioni intraprese sulla base del Servizio." },
      { type: "p", text: "Queste limitazioni si applicano solo nella misura consentita dalla legge applicabile." },
      { type: "h2", text: "7. Risoluzione" },
      { type: "p", text: "Ci riserviamo il diritto di sospendere o terminare immediatamente l'accesso al Servizio, senza preavviso, in caso di violazione dei presenti Termini, in particolare per quanto riguarda l'estrazione massiva non autorizzata di dati o la violazione dei diritti di terzi." },
      { type: "h2", text: "8. Disposizioni Generali" },
      { type: "p", text: "8.1. Clausola di Salvaguardia: Se una disposizione dei presenti Termini risulta inapplicabile o non valida, tale disposizione sarà limitata o eliminata nella misura minima necessaria affinché i presenti Termini rimangano pienamente in vigore ed efficaci." },
      { type: "p", text: "8.2. Modifiche ai Termini: Ci riserviamo il diritto di modificare i presenti Termini in qualsiasi momento a nostra esclusiva discrezione. L'uso continuato del Servizio successivamente a qualsiasi modifica costituisce accettazione dei nuovi Termini." },
      { type: "h2", text: "9. Legge Applicabile e Foro Competente" },
      { type: "p", text: "I presenti Termini sono regolati dalle leggi italiane. Qualsiasi controversia derivante dai presenti Termini sarà soggetta alla giurisdizione esclusiva dei tribunali competenti di Roma, Italia. I consumatori europei hanno il diritto di utilizzare la piattaforma di Risoluzione delle Controversie Online." },
    ],
  },
  es: {
    title: "Términos de Servicio",
    lastUpdated: "Última actualización: 01 de febrero de 2026",
    description: "Términos de Servicio para la extensión de navegador GetNearMe.",
    blocks: [
      { type: "h2", text: "1. Aceptación de los Términos" },
      { type: "p", text: "Al instalar o usar la extensión GetNearMe (\"Servicio\"), usted acepta quedar vinculado por estos Términos de Servicio (\"Términos\"). Usted afirma que tiene al menos 18 años de edad y que es plenamente capaz y competente para celebrar este acuerdo. Si no está de acuerdo, debe desinstalar inmediatamente el Servicio." },
      { type: "h2", text: "2. Licencia y Naturaleza del Servicio" },
      { type: "p", text: "2.1. Utilidad del Lado del Cliente: Usted reconoce que el Servicio opera como un \"User Agent\" o utilidad del navegador bajo su control directo. Está diseñado para mejorar su experiencia de navegación local visualizando información independiente del mercado." },
      { type: "p", text: "2.2. Licencia Limitada: Le otorgamos una licencia revocable, no exclusiva e intransferible para usar el Servicio exclusivamente para su análisis personal o empresarial interno de datos del mercado inmobiliario." },
      { type: "h2", text: "3. Restricciones y Propiedad Intelectual" },
      { type: "p", text: "3.1. Independencia: GetNearMe es una herramienta de software independiente. No estamos afiliados, respaldados, patrocinados ni oficialmente conectados con ninguna plataforma inmobiliaria (como Immobiliare.it, Idealista u otras). Todas las marcas comerciales de terceros son propiedad de sus respectivos titulares y se utilizan exclusivamente con fines descriptivos de compatibilidad (Nominative Fair Use)." },
      { type: "p", text: "3.2. Conducta Prohibida: Usted acepta explícitamente NO utilizar el Servicio para:" },
      { type: "ul", items: [
        "Realizar extracción masiva de datos con el propósito de crear una base de datos competidora, motor de búsqueda o servicio comercial.",
        "Eludir medidas de seguridad, CAPTCHAs o barreras de autenticación de plataformas de terceros.",
        "Violar los Términos de Servicio de cualquier portal inmobiliario de terceros visitado mientras se usa la Extensión.",
        "Intentar eludir, desactivar o vencer cualquier restricción técnica o medida de protección de contenido implementada en el Servicio (incluidas las restricciones de impresión, copia o exportación de datos)."
      ]},
      { type: "h2", text: "4. Exclusiones y Limitaciones de Responsabilidad" },
      { type: "p", text: "4.1. Valores Estimados: Cualquier \"Total Estimado\" o cálculo financiero proporcionado por el Servicio representa una estimación indicativa de costos asociados con la compra de una propiedad (ej. comisiones de agencia, costos notariales, impuestos). Estas estimaciones son solo para fines informativos y no constituyen una oferta vinculante o una cotización financiera profesional." },
      { type: "p", text: "4.2. Fiabilidad de los Datos: La información visualizada por el Servicio se deriva de datos públicamente disponibles, información presente en los anuncios analizados y procesamiento automático. No verificamos las clases energéticas mediante certificados oficiales (APE) ni garantizamos la exactitud de los datos en los anuncios de origen. Las inexactitudes u omisiones en el anuncio original de terceros pueden reflejarse en el informe del Servicio." },
      { type: "p", text: "4.3. Sin Asesoramiento Profesional: El Servicio no sustituye la verificación técnica, legal, fiscal o inmobiliaria realizada por profesionales cualificados. En la medida permitida por la ley aplicable, GetNearMe no asume responsabilidad por las decisiones tomadas basándose en la información proporcionada." },
      { type: "h2", text: "5. Créditos, Pagos y Reembolsos" },
      { type: "p", text: "5.1. Compra de Créditos: El Servicio opera con un sistema basado en créditos. Los créditos son unidades virtuales utilizadas exclusivamente para desbloquear funciones o análisis específicos dentro de la Extensión. Los créditos no representan fondos prepagados, dinero electrónico o valor almacenado, no tienen valor monetario fuera del Servicio y no pueden canjearse por efectivo, reembolsarse ni transferirse a otras cuentas." },
      { type: "p", text: "5.2. Procesamiento de Pagos: Todos los pagos son procesados de forma segura y exclusivamente por Stripe de acuerdo con sus propios términos y políticas de privacidad. GetNearMe no almacena ni tiene acceso a los datos completos de las tarjetas de pago de los usuarios. Al comprar créditos, usted autoriza a Stripe a cobrar su método de pago seleccionado por el monto aplicable." },
      { type: "p", text: "5.3. Renuncia al Derecho de Desistimiento: Al comprar créditos digitales, usted consiente expresamente la ejecución inmediata del contrato y reconoce expresamente que, una vez que los créditos son acreditados en su cuenta, pierde su derecho de desistimiento (período de reflexión) de acuerdo con el Artículo 16(m) de la Directiva 2011/83/UE sobre Derechos de los Consumidores." },
      { type: "p", text: "5.4. Política de Reembolso: Todas las compras de créditos son definitivas y no reembolsables, excepto cuando las leyes obligatorias de protección al consumidor dispongan lo contrario. No se emitirán reembolsos por créditos no utilizados o si decide dejar de usar el Servicio." },
      { type: "p", text: "En caso de error técnico comprobado atribuible exclusivamente a GetNearMe (por ejemplo, créditos pagados pero no acreditados en la cuenta del usuario), el usuario puede contactar con soporte en as.scirica@gmail.com para verificación y rectificación." },
      { type: "h2", text: "6. Responsabilidad" },
      { type: "p", text: "En la máxima medida permitida por la ley aplicable, GetNearMe no será responsable de daños indirectos, incidentales, especiales o consecuentes, incluida la pérdida de beneficios, datos, uso o fondo de comercio, que surjan del uso o la imposibilidad de uso del Servicio." },
      { type: "p", text: "El Servicio se proporciona únicamente con fines informativos e ilustrativos y se basa en información públicamente disponible, plataformas de terceros y procesamiento automatizado. GetNearMe no garantiza la exactitud, integridad o disponibilidad de ninguna información, estimación o resultado generado por IA y no es responsable de las decisiones o acciones tomadas basándose en el Servicio." },
      { type: "p", text: "Estas limitaciones se aplican solo en la medida permitida por la ley aplicable." },
      { type: "h2", text: "7. Terminación" },
      { type: "p", text: "Nos reservamos el derecho de suspender o terminar su acceso al Servicio inmediatamente, sin previo aviso, si incumple estos Términos, particularmente en lo que respecta a la extracción masiva no autorizada de datos o la violación de derechos de terceros." },
      { type: "h2", text: "8. Disposiciones Generales" },
      { type: "p", text: "8.1. Separabilidad: Si alguna disposición de estos Términos resulta inaplicable o inválida, dicha disposición será limitada o eliminada en la medida mínima necesaria para que estos Términos permanezcan en pleno vigor y efecto." },
      { type: "p", text: "8.2. Cambios en los Términos: Nos reservamos el derecho de modificar estos Términos en cualquier momento a nuestra entera discreción. El uso continuado del Servicio tras cualquier cambio constituye su aceptación de los nuevos Términos." },
      { type: "h2", text: "9. Ley Aplicable y Jurisdicción" },
      { type: "p", text: "Estos Términos se regirán por las leyes de Italia. Cualquier disputa que surja de estos Términos estará sujeta a la jurisdicción exclusiva de los tribunales competentes de Roma, Italia. Los consumidores europeos tienen derecho a utilizar la plataforma de Resolución de Disputas en Línea." },
    ],
  },
  fr: {
    title: "Conditions d'Utilisation",
    lastUpdated: "Dernière mise à jour : 01 février 2026",
    description: "Conditions d'Utilisation pour l'extension de navigateur GetNearMe.",
    blocks: [
      { type: "h2", text: "1. Acceptation des Conditions" },
      { type: "p", text: "En installant ou en utilisant l'extension GetNearMe (\"Service\"), vous acceptez d'être lié par les présentes Conditions d'Utilisation (\"Conditions\"). Vous affirmez avoir au moins 18 ans et être pleinement capable et compétent pour conclure cet accord. Si vous n'êtes pas d'accord, vous devez immédiatement désinstaller le Service." },
      { type: "h2", text: "2. Licence et Nature du Service" },
      { type: "p", text: "2.1. Utilitaire Côté Client : Vous reconnaissez que le Service fonctionne comme un \"User Agent\" ou un utilitaire de navigateur sous votre contrôle direct. Il est conçu pour améliorer votre expérience de navigation locale en visualisant des informations de marché indépendantes." },
      { type: "p", text: "2.2. Licence Limitée : Nous vous accordons une licence révocable, non exclusive et non transférable pour utiliser le Service uniquement pour votre analyse personnelle ou professionnelle interne de données du marché immobilier." },
      { type: "h2", text: "3. Restrictions et Propriété Intellectuelle" },
      { type: "p", text: "3.1. Indépendance : GetNearMe est un outil logiciel indépendant. Nous ne sommes affiliés, approuvés, sponsorisés ni officiellement liés à aucune plateforme immobilière (telle qu'Immobiliare.it, Idealista ou d'autres). Toutes les marques de tiers sont la propriété de leurs détenteurs respectifs et sont utilisées uniquement à des fins descriptives de compatibilité (Nominative Fair Use)." },
      { type: "p", text: "3.2. Conduite Interdite : Vous acceptez explicitement de NE PAS utiliser le Service pour :" },
      { type: "ul", items: [
        "Effectuer une extraction massive de données dans le but de créer une base de données concurrente, un moteur de recherche ou un service commercial.",
        "Contourner les mesures de sécurité, CAPTCHAs ou barrières d'authentification de plateformes tierces.",
        "Violer les Conditions d'Utilisation de tout portail immobilier tiers visité lors de l'utilisation de l'Extension.",
        "Tenter de contourner, désactiver ou vaincre toute restriction technique ou mesure de protection du contenu mise en œuvre dans le Service (y compris les restrictions d'impression, de copie ou d'exportation de données)."
      ]},
      { type: "h2", text: "4. Exclusions et Limitations de Responsabilité" },
      { type: "p", text: "4.1. Valeurs Estimées : Tout \"Total Estimé\" ou calcul financier fourni par le Service représente une estimation indicative des coûts associés à l'achat d'un bien immobilier (ex. frais d'agence, frais de notaire, taxes). Ces estimations sont fournies à titre informatif uniquement et ne constituent pas une offre contraignante ou un devis financier professionnel." },
      { type: "p", text: "4.2. Fiabilité des Données : Les informations visualisées par le Service proviennent de données publiquement disponibles, d'informations présentes dans les annonces analysées et d'un traitement automatique. Nous ne vérifions pas les classes énergétiques via des certificats officiels (APE) et ne garantissons pas l'exactitude des données dans les annonces sources. Les inexactitudes ou omissions dans l'annonce originale du tiers peuvent se refléter dans le rapport du Service." },
      { type: "p", text: "4.3. Pas de Conseil Professionnel : Le Service ne remplace pas la vérification technique, juridique, fiscale ou immobilière effectuée par des professionnels qualifiés. Dans la mesure permise par la loi applicable, GetNearMe n'assume aucune responsabilité pour les décisions prises sur la base des informations fournies." },
      { type: "h2", text: "5. Crédits, Paiements et Remboursements" },
      { type: "p", text: "5.1. Achat de Crédits : Le Service fonctionne sur un système de crédits. Les crédits sont des unités virtuelles utilisées uniquement pour débloquer des fonctionnalités ou analyses spécifiques au sein de l'Extension. Les crédits ne représentent pas des fonds prépayés, de la monnaie électronique ou de la valeur stockée, n'ont aucune valeur monétaire en dehors du Service et ne peuvent être échangés contre de l'argent, remboursés ou transférés à d'autres comptes." },
      { type: "p", text: "5.2. Traitement des Paiements : Tous les paiements sont traités de manière sécurisée et exclusivement par Stripe conformément à ses propres conditions et politiques de confidentialité. GetNearMe ne stocke pas et n'a pas accès aux détails complets des cartes de paiement des utilisateurs. En achetant des crédits, vous autorisez Stripe à débiter votre moyen de paiement sélectionné du montant applicable." },
      { type: "p", text: "5.3. Renonciation au Droit de Rétractation : En achetant des crédits numériques, vous consentez expressément à l'exécution immédiate du contrat et reconnaissez expressément que, une fois les crédits crédités sur votre compte, vous perdez votre droit de rétractation (délai de réflexion) conformément à l'Article 16(m) de la Directive 2011/83/UE relative aux Droits des Consommateurs." },
      { type: "p", text: "5.4. Politique de Remboursement : Tous les achats de crédits sont définitifs et non remboursables, sauf disposition contraire des lois obligatoires de protection des consommateurs. Aucun remboursement ne sera émis pour les crédits non utilisés ou si vous choisissez de cesser d'utiliser le Service." },
      { type: "p", text: "En cas d'erreur technique prouvée attribuable exclusivement à GetNearMe (par exemple, crédits payés mais non crédités sur le compte de l'utilisateur), l'utilisateur peut contacter le support à as.scirica@gmail.com pour vérification et rectification." },
      { type: "h2", text: "6. Responsabilité" },
      { type: "p", text: "Dans la mesure maximale permise par la loi applicable, GetNearMe ne sera pas responsable de tout dommage indirect, accessoire, spécial ou consécutif, y compris la perte de profits, de données, d'utilisation ou de clientèle, résultant de l'utilisation ou de l'impossibilité d'utiliser le Service." },
      { type: "p", text: "Le Service est fourni à des fins informatives et illustratives uniquement et repose sur des informations publiquement disponibles, des plateformes tierces et un traitement automatisé. GetNearMe ne garantit pas l'exactitude, l'exhaustivité ou la disponibilité de toute information, estimation ou résultat généré par l'IA et n'est pas responsable des décisions ou actions entreprises sur la base du Service." },
      { type: "p", text: "Ces limitations ne s'appliquent que dans la mesure permise par la loi applicable." },
      { type: "h2", text: "7. Résiliation" },
      { type: "p", text: "Nous nous réservons le droit de suspendre ou de résilier votre accès au Service immédiatement, sans préavis, si vous enfreignez les présentes Conditions, notamment en ce qui concerne l'extraction massive non autorisée de données ou la violation des droits de tiers." },
      { type: "h2", text: "8. Dispositions Générales" },
      { type: "p", text: "8.1. Divisibilité : Si une disposition des présentes Conditions est jugée inapplicable ou invalide, cette disposition sera limitée ou éliminée dans la mesure minimale nécessaire afin que les présentes Conditions restent pleinement en vigueur et effet." },
      { type: "p", text: "8.2. Modifications des Conditions : Nous nous réservons le droit de modifier les présentes Conditions à tout moment à notre seule discrétion. L'utilisation continue du Service après toute modification constitue votre acceptation des nouvelles Conditions." },
      { type: "h2", text: "9. Droit Applicable et Juridiction" },
      { type: "p", text: "Les présentes Conditions sont régies par les lois de l'Italie. Tout litige découlant des présentes Conditions sera soumis à la juridiction exclusive des tribunaux compétents de Rome, Italie. Les consommateurs européens ont le droit d'utiliser la plateforme de Résolution des Litiges en Ligne." },
    ],
  },
  ru: {
    title: "Условия использования",
    lastUpdated: "Последнее обновление: 01 февраля 2026",
    description: "Условия использования расширения браузера GetNearMe.",
    blocks: [
      { type: "h2", text: "1. Принятие условий" },
      { type: "p", text: "Устанавливая или используя расширение GetNearMe (\"Сервис\"), вы соглашаетесь соблюдать настоящие Условия использования (\"Условия\"). Вы подтверждаете, что вам исполнилось 18 лет и вы полностью дееспособны для заключения данного соглашения. Если вы не согласны, вы должны немедленно удалить Сервис." },
      { type: "h2", text: "2. Лицензия и характер Сервиса" },
      { type: "p", text: "2.1. Клиентская утилита: Вы признаёте, что Сервис работает как \"User Agent\" или утилита браузера под вашим непосредственным контролем. Он предназначен для улучшения вашего локального просмотра путём визуализации независимой рыночной аналитики." },
      { type: "p", text: "2.2. Ограниченная лицензия: Мы предоставляем вам отзывную, неисключительную, непередаваемую лицензию на использование Сервиса исключительно для личного или внутреннего делового анализа данных рынка недвижимости." },
      { type: "h2", text: "3. Ограничения и интеллектуальная собственность" },
      { type: "p", text: "3.1. Независимость: GetNearMe является независимым программным инструментом. Мы не аффилированы, не одобрены, не спонсированы и не связаны официально ни с одной платформой недвижимости (такой как Immobiliare.it, Idealista или другие). Все товарные знаки третьих лиц являются собственностью их соответствующих владельцев и используются исключительно в описательных целях совместимости (Nominative Fair Use)." },
      { type: "p", text: "3.2. Запрещённые действия: Вы явно соглашаетесь НЕ использовать Сервис для:" },
      { type: "ul", items: [
        "Массового извлечения данных с целью создания конкурирующей базы данных, поисковой системы или коммерческого сервиса.",
        "Обхода мер безопасности, CAPTCHA или барьеров аутентификации сторонних платформ.",
        "Нарушения Условий использования любого стороннего портала недвижимости, посещаемого при использовании Расширения.",
        "Попытки обойти, отключить или преодолеть любые технические ограничения или меры защиты контента, реализованные в Сервисе (включая ограничения на печать, копирование или экспорт данных)."
      ]},
      { type: "h2", text: "4. Отказ от ответственности и ограничения" },
      { type: "p", text: "4.1. Оценочные значения: Любой \"Расчётный итог\" или финансовый расчёт, предоставленный Сервисом, представляет собой ориентировочную оценку затрат, связанных с покупкой недвижимости (напр., агентские комиссии, нотариальные расходы, налоги). Эти оценки носят исключительно информационный характер и не являются обязывающим предложением или профессиональной финансовой котировкой." },
      { type: "p", text: "4.2. Достоверность данных: Информация, визуализируемая Сервисом, основана на общедоступных данных, информации из анализируемых объявлений и автоматической обработке. Мы не проверяем энергетические классы через официальные сертификаты (APE) и не гарантируем точность данных в исходных объявлениях. Неточности или пропуски в оригинальном стороннем объявлении могут отразиться в отчёте Сервиса." },
      { type: "p", text: "4.3. Отсутствие профессиональной консультации: Сервис не заменяет техническую, юридическую, налоговую или риэлторскую проверку, выполняемую квалифицированными специалистами. В пределах, допускаемых применимым законодательством, GetNearMe не несёт ответственности за решения, принятые на основе предоставленной информации." },
      { type: "h2", text: "5. Кредиты, платежи и возвраты" },
      { type: "p", text: "5.1. Покупка кредитов: Сервис работает на системе кредитов. Кредиты — это виртуальные единицы, используемые исключительно для разблокировки определённых функций или аналитики в Расширении. Кредиты не являются предоплаченными средствами, электронными деньгами или сохранённой стоимостью, не имеют денежной ценности вне Сервиса и не могут быть обменяны на наличные, возвращены или переведены на другие аккаунты." },
      { type: "p", text: "5.2. Обработка платежей: Все платежи обрабатываются безопасно и исключительно Stripe в соответствии с его собственными условиями и политиками конфиденциальности. GetNearMe не хранит и не имеет доступа к полным данным платёжных карт пользователей. Приобретая кредиты, вы уполномочиваете Stripe списать средства с выбранного способа оплаты на применимую сумму." },
      { type: "p", text: "5.3. Отказ от права на отзыв: Приобретая цифровые кредиты, вы явно соглашаетесь на немедленное исполнение договора и явно признаёте, что после зачисления кредитов на ваш аккаунт вы теряете право на отзыв (период обдумывания) в соответствии со Статьёй 16(m) Директивы 2011/83/ЕС о правах потребителей." },
      { type: "p", text: "5.4. Политика возврата: Все покупки кредитов являются окончательными и невозвратными, за исключением случаев, предусмотренных обязательным законодательством о защите прав потребителей. Возвраты не производятся за неиспользованные кредиты или при прекращении использования Сервиса." },
      { type: "p", text: "В случае подтверждённой технической ошибки, относящейся исключительно к GetNearMe (например, кредиты оплачены, но не зачислены на аккаунт пользователя), пользователь может обратиться в поддержку по адресу as.scirica@gmail.com для проверки и исправления." },
      { type: "h2", text: "6. Ответственность" },
      { type: "p", text: "В максимальной степени, допускаемой применимым законодательством, GetNearMe не несёт ответственности за любые косвенные, побочные, особые или последующие убытки, включая упущенную выгоду, потерю данных, использования или деловой репутации, возникающие в связи с использованием или невозможностью использования Сервиса." },
      { type: "p", text: "Сервис предоставляется исключительно в информационных и иллюстративных целях и основан на общедоступной информации, сторонних платформах и автоматизированной обработке. GetNearMe не гарантирует точность, полноту или доступность какой-либо информации, оценок или результатов, сгенерированных ИИ, и не несёт ответственности за решения или действия, предпринятые на основе Сервиса." },
      { type: "p", text: "Эти ограничения применяются только в пределах, допускаемых применимым законодательством." },
      { type: "h2", text: "7. Прекращение" },
      { type: "p", text: "Мы оставляем за собой право немедленно приостановить или прекратить ваш доступ к Сервису без предварительного уведомления в случае нарушения настоящих Условий, особенно в отношении несанкционированного массового извлечения данных или нарушения прав третьих лиц." },
      { type: "h2", text: "8. Общие положения" },
      { type: "p", text: "8.1. Делимость: Если какое-либо положение настоящих Условий будет признано неисполнимым или недействительным, это положение будет ограничено или исключено в минимально необходимой степени, чтобы настоящие Условия в остальном сохраняли полную силу и действие." },
      { type: "p", text: "8.2. Изменение Условий: Мы оставляем за собой право изменять настоящие Условия в любое время по нашему собственному усмотрению. Продолжение использования Сервиса после любых изменений означает ваше принятие новых Условий." },
      { type: "h2", text: "9. Применимое право и юрисдикция" },
      { type: "p", text: "Настоящие Условия регулируются законодательством Италии. Любой спор, вытекающий из настоящих Условий, подлежит исключительной юрисдикции компетентных судов Рима, Италия. Европейские потребители имеют право использовать платформу Онлайн-разрешения споров." },
    ],
  },
  uk: {
    title: "Умови використання",
    lastUpdated: "Останнє оновлення: 01 лютого 2026",
    description: "Умови використання розширення браузера GetNearMe.",
    blocks: [
      { type: "h2", text: "1. Прийняття умов" },
      { type: "p", text: "Встановлюючи або використовуючи розширення GetNearMe (\"Сервіс\"), ви погоджуєтесь дотримуватись цих Умов використання (\"Умови\"). Ви підтверджуєте, що вам виповнилось 18 років і ви повністю дієздатні для укладення цієї угоди. Якщо ви не погоджуєтесь, ви повинні негайно видалити Сервіс." },
      { type: "h2", text: "2. Ліцензія та характер Сервісу" },
      { type: "p", text: "2.1. Клієнтська утиліта: Ви визнаєте, що Сервіс працює як \"User Agent\" або утиліта браузера під вашим безпосереднім контролем. Він призначений для покращення вашого локального перегляду шляхом візуалізації незалежної ринкової аналітики." },
      { type: "p", text: "2.2. Обмежена ліцензія: Ми надаємо вам відкличну, невиключну, непередавану ліцензію на використання Сервісу виключно для особистого або внутрішнього ділового аналізу даних ринку нерухомості." },
      { type: "h2", text: "3. Обмеження та інтелектуальна власність" },
      { type: "p", text: "3.1. Незалежність: GetNearMe є незалежним програмним інструментом. Ми не афілійовані, не схвалені, не спонсоровані та не пов'язані офіційно з жодною платформою нерухомості (такою як Immobiliare.it, Idealista або інші). Усі товарні знаки третіх осіб є власністю їхніх відповідних власників і використовуються виключно в описових цілях сумісності (Nominative Fair Use)." },
      { type: "p", text: "3.2. Заборонені дії: Ви явно погоджуєтесь НЕ використовувати Сервіс для:" },
      { type: "ul", items: [
        "Масового видобування даних з метою створення конкуруючої бази даних, пошукової системи або комерційного сервісу.",
        "Обходу заходів безпеки, CAPTCHA або бар'єрів автентифікації сторонніх платформ.",
        "Порушення Умов використання будь-якого стороннього порталу нерухомості, відвідуваного при використанні Розширення.",
        "Спроби обійти, вимкнути або подолати будь-які технічні обмеження або заходи захисту контенту, реалізовані в Сервісі (включаючи обмеження на друк, копіювання або експорт даних)."
      ]},
      { type: "h2", text: "4. Застереження та обмеження відповідальності" },
      { type: "p", text: "4.1. Оціночні значення: Будь-який \"Розрахунковий підсумок\" або фінансовий розрахунок, наданий Сервісом, являє собою орієнтовну оцінку витрат, пов'язаних з придбанням нерухомості (напр., агентські комісії, нотаріальні витрати, податки). Ці оцінки носять виключно інформаційний характер і не є обов'язковою пропозицією або професійною фінансовою котировкою." },
      { type: "p", text: "4.2. Достовірність даних: Інформація, візуалізована Сервісом, базується на загальнодоступних даних, інформації з аналізованих оголошень та автоматичній обробці. Ми не перевіряємо енергетичні класи через офіційні сертифікати (APE) і не гарантуємо точність даних у вихідних оголошеннях. Неточності або пропуски в оригінальному сторонньому оголошенні можуть відобразитися у звіті Сервісу." },
      { type: "p", text: "4.3. Відсутність професійної консультації: Сервіс не замінює технічну, юридичну, податкову або ріелторську перевірку, виконувану кваліфікованими фахівцями. У межах, допустимих чинним законодавством, GetNearMe не несе відповідальності за рішення, прийняті на основі наданої інформації." },
      { type: "h2", text: "5. Кредити, платежі та повернення" },
      { type: "p", text: "5.1. Придбання кредитів: Сервіс працює на системі кредитів. Кредити — це віртуальні одиниці, що використовуються виключно для розблокування певних функцій або аналітики в Розширенні. Кредити не є передоплаченими коштами, електронними грошима або збереженою вартістю, не мають грошової цінності поза Сервісом і не можуть бути обміняні на готівку, повернені або переведені на інші акаунти." },
      { type: "p", text: "5.2. Обробка платежів: Усі платежі обробляються безпечно та виключно Stripe відповідно до його власних умов та політик конфіденційності. GetNearMe не зберігає та не має доступу до повних даних платіжних карток користувачів. Купуючи кредити, ви уповноважуєте Stripe списати кошти з обраного способу оплати на відповідну суму." },
      { type: "p", text: "5.3. Відмова від права на відкликання: Купуючи цифрові кредити, ви явно погоджуєтесь на негайне виконання договору та явно визнаєте, що після зарахування кредитів на ваш акаунт ви втрачаєте право на відкликання (період обдумування) відповідно до Статті 16(m) Директиви 2011/83/ЄС про права споживачів." },
      { type: "p", text: "5.4. Політика повернення: Усі покупки кредитів є остаточними та неповоротними, за винятком випадків, передбачених обов'язковим законодавством про захист прав споживачів. Повернення не здійснюються за невикористані кредити або при припиненні використання Сервісу." },
      { type: "p", text: "У разі підтвердженої технічної помилки, що відноситься виключно до GetNearMe (наприклад, кредити оплачені, але не зараховані на акаунт користувача), користувач може звернутися до підтримки за адресою as.scirica@gmail.com для перевірки та виправлення." },
      { type: "h2", text: "6. Відповідальність" },
      { type: "p", text: "У максимальному обсязі, допустимому чинним законодавством, GetNearMe не несе відповідальності за будь-які непрямі, випадкові, особливі або наслідкові збитки, включаючи втрату прибутку, даних, використання або ділової репутації, що виникають у зв'язку з використанням або неможливістю використання Сервісу." },
      { type: "p", text: "Сервіс надається виключно в інформаційних та ілюстративних цілях і базується на загальнодоступній інформації, сторонніх платформах та автоматизованій обробці. GetNearMe не гарантує точність, повноту або доступність будь-якої інформації, оцінок або результатів, згенерованих ШІ, і не несе відповідальності за рішення або дії, вжиті на основі Сервісу." },
      { type: "p", text: "Ці обмеження застосовуються лише в межах, допустимих чинним законодавством." },
      { type: "h2", text: "7. Припинення" },
      { type: "p", text: "Ми залишаємо за собою право негайно призупинити або припинити ваш доступ до Сервісу без попереднього повідомлення у разі порушення цих Умов, зокрема щодо несанкціонованого масового видобування даних або порушення прав третіх осіб." },
      { type: "h2", text: "8. Загальні положення" },
      { type: "p", text: "8.1. Подільність: Якщо будь-яке положення цих Умов буде визнано нездійсненним або недійсним, це положення буде обмежене або виключене в мінімально необхідному обсязі, щоб ці Умови в іншому залишались у повній силі та дії." },
      { type: "p", text: "8.2. Зміна Умов: Ми залишаємо за собою право змінювати ці Умови в будь-який час на наш власний розсуд. Продовження використання Сервісу після будь-яких змін означає ваше прийняття нових Умов." },
      { type: "h2", text: "9. Застосовне право та юрисдикція" },
      { type: "p", text: "Ці Умови регулюються законодавством Італії. Будь-який спір, що виникає з цих Умов, підлягає виключній юрисдикції компетентних судів Риму, Італія. Європейські споживачі мають право використовувати платформу Онлайн-вирішення спорів." },
    ],
  },
};
