// Prompt di home staging, portati dalle edge function Nano Banana di GetNearMe
// (GetNearMe/supabase/functions/replicate-staging): stessi 6 stili x interno/facciata/giardino,
// le 6 viste, la planimetria e le protezioni per il testo libero. Qui li usa Qwen-Image
// (/api/platform/photo-edit). Il tipo di stanza per gli interni vuoti non c'e' ancora:
// sulle edge function lo classificava Groq, qui arriva quando ci serve.

export type SceneType = 'interno' | 'esterno' | 'giardino';

const STYLE_PROMPTS: Record<string, string> = {
  modern: "Edit this image to professionally stage the interior in a Modern Contemporary style. If the room already contains furniture, replace each existing piece ONLY with a modern contemporary version of the SAME item category. If the room is EMPTY or only sparsely furnished, FULLY FURNISH it with appropriate modern contemporary furniture matched to the room's function (living room: sofa, armchairs, coffee table, rug, sideboard, lamps and decor; bedroom: bed, nightstands, wardrobe; dining area: dining table and chairs; kitchen: styled accessories), arranged realistically and to scale so the room looks complete and livable. STRICT RULES: Do NOT modify walls, windows, doors, ceiling, floor, or architecture. Preserve the original camera angle, perspective and room proportions. Modern Contemporary style: clean geometric lines, neutral base palette with bold accent colors, designer statement pieces, sleek metal and glass combinations, minimalist silhouettes, matte and gloss contrast finishes, integrated LED lighting, open airy feel, curated art pieces, monochromatic schemes with pops of color. Atmosphere: sophisticated, fresh, urban chic, architectural digest aesthetic, high-end modern living, designer showroom quality. Photorealistic, ultra realistic, cinematic interior lighting, highly detailed, architectural visualization quality, 8k.",
  nordic: "Edit this photo to professionally stage the interior in a Scandinavian Nordic style. If the room already contains furniture, replace each existing piece with a Nordic version of the same item. If the room is EMPTY or only sparsely furnished, FULLY FURNISH it with appropriate Nordic furniture matched to the room's function (living room: sofa, armchair, coffee table, rug, shelving, lamps and decor; bedroom: bed, nightstands, wardrobe; dining area: dining table and chairs), arranged realistically and to scale so the room looks complete and livable. Nordic style: light oak/birch wood, white and grey palette, minimal functional pieces, wool/linen textiles, clean uncluttered look. DO NOT modify walls, doors, windows, ceiling, floor or any architectural element. Preserve the original camera angle, perspective and room proportions. Photorealistic, 8k.",
  industrial: "Edit this image to professionally stage the interior in a Luxury Contemporary style. If the room already contains furniture, replace each existing piece ONLY with a high-end luxury contemporary version of the SAME item category. If the room is EMPTY or only sparsely furnished, FULLY FURNISH it with appropriate high-end luxury contemporary furniture matched to the room's function (living room: sofa, armchairs, coffee table, rug, sideboard, lamps and decor; bedroom: bed, nightstands, wardrobe; dining area: dining table and chairs), arranged realistically and to scale so the room looks complete and livable. STRICT RULES: Do NOT modify walls, windows, doors, ceiling, floor, or architecture. Preserve the original camera angle, perspective and room proportions. Luxury Contemporary style: premium marble, travertine, brushed brass accents, smoked glass, dark walnut wood, oak finishes, soft ambient lighting, elegant textures, neutral luxury palette, sophisticated minimalist furniture, hotel-suite aesthetic, upscale residential interior design. Atmosphere: refined, elegant, warm luxury, architectural digest aesthetic, high-end real estate staging, modern luxury apartment design. Photorealistic, ultra realistic, cinematic interior lighting, highly detailed, architectural visualization quality, 8k.",
  boho: "Edit this photo to professionally stage the interior in a Bohemian style. If the room already contains furniture, replace each existing piece with a boho version of the same item. If the room is EMPTY or only sparsely furnished, FULLY FURNISH it with appropriate boho furniture matched to the room's function (living room: sofa, armchair, coffee table, rug, shelving, plants and decor; bedroom: bed, nightstands, wardrobe; dining area: dining table and chairs), arranged realistically and to scale so the room looks complete and livable. Bohemian style: rattan, wicker, macramé, natural wood, indoor plants, earthy tones, jute, bamboo, eclectic patterns. DO NOT modify walls, doors, windows, ceiling, floor or any architectural element. Preserve the original camera angle, perspective and room proportions. Photorealistic, 8k.",
  daynight: "Analyze the lighting in this photo. If daytime: convert to nighttime — dark blue sky through windows, all light fixtures ON with warm glow and halos, deep shadows. If nighttime: convert to daytime — bright blue sky, natural sunlight through windows, morning light. CRITICAL: do NOT add, remove, move or change ANY object, furniture, door, window or wall. ONLY change lighting and sky. Photorealistic, 8k.",
  empty: "Edit this photo to show this EXACT room COMPLETELY EMPTY and unfurnished, like a vacant apartment ready for viewing before anyone has moved in. REMOVE ABSOLUTELY EVERYTHING that is not part of the building structure — nothing movable may remain. Remove every: sofa, couch, armchair, chair, stool, bench, bed, mattress, table, desk, coffee table, cabinet, wardrobe, closet, shelf, bookcase, dresser, nightstand, TV and TV stand, free-standing kitchen units and appliances, rug, carpet, curtain, blind, lamp, chandelier, floor light, plant, flower, vase, pot, tree, greenery, painting, poster, photo frame, mirror, wall decoration, clock, cushion, pillow, blanket, book, box, toy and every personal item. The room must look totally bare: only empty floor, bare walls and ceiling. Reconstruct clean, continuous, realistic floor and wall surfaces wherever an object stood, matching the existing materials, colors and lighting (no holes, shadows or ghost outlines of removed objects). KEEP EXACTLY AS-IS and unchanged: all walls, windows, doors, ceiling, floor material, baseboards, built-in radiators, wall electrical outlets and switches, and any permanently built-in fixtures — identical in number, position, shape, size and color. DO NOT add or remove any wall, door or window, and DO NOT change the room shape, perspective or camera angle. Photorealistic, fully empty vacant room, 8k.",
};

const STYLE_PROMPTS_ESTERNO: Record<string, string> = {
  modern: "Edit this photo of a house exterior/facade: restyle it in a Modern Contemporary architectural style. Change the facade render, cladding and paint to clean neutral tones (white, grey, anthracite), sleek dark-framed windows and doors, minimalist entrance, clean geometric lines. STRICT RULES: preserve EXACTLY the building's structure, roofline, the position and size of every window and door, the number of floors, and the camera angle/perspective. Do NOT add, remove or resize any window, door or architectural opening. Only restyle materials, colors and finishes. Photorealistic, 8k.",
  nordic: "Edit this photo of a house exterior/facade: restyle it in a Scandinavian Nordic exterior style. Light timber cladding, white or pale grey render, black window frames, minimal clean entrance, natural wood accents. STRICT RULES: preserve EXACTLY the building's structure, roofline, the position and size of every window and door, the number of floors, and the camera angle/perspective. Do NOT add, remove or resize any window, door or architectural opening. Only restyle materials, colors and finishes. Photorealistic, 8k.",
  industrial: "Edit this photo of a house exterior/facade: restyle it in a Luxury Contemporary exterior style. Premium stone or travertine cladding, brushed metal accents, elegant entrance lighting, sophisticated dark or warm-toned palette. STRICT RULES: preserve EXACTLY the building's structure, roofline, the position and size of every window and door, the number of floors, and the camera angle/perspective. Do NOT add, remove or resize any window, door or architectural opening. Only restyle materials, colors and finishes. Photorealistic, 8k.",
  boho: "Edit this photo of a house exterior/facade: restyle it in a Mediterranean villa exterior style. Warm terracotta or ochre stucco render, white or pastel trim, wooden shutters, terracotta roof tiles, climbing plants near the entrance. STRICT RULES: preserve EXACTLY the building's structure, roofline, the position and size of every window and door, the number of floors, and the camera angle/perspective. Do NOT add, remove or resize any window, door or architectural opening. Only restyle materials, colors and finishes. Photorealistic, 8k.",
  daynight: "Analyze the lighting in this photo of a building exterior/facade. If daytime: convert to nighttime — dark sky, warm exterior lights ON (entrance lights, facade uplighting, warm glow from windows), landscape lighting. If nighttime: convert to daytime — bright blue sky, natural sunlight on the facade. CRITICAL: do NOT add, remove, move or change any structural element, window, door or wall. ONLY change lighting and sky. Photorealistic, 8k.",
  empty: "Edit this photo to FULLY RENOVATE and restore the building facade to a like-new condition. MANDATORY: repair and completely smooth over EVERY crack, fissure, water stain, mold patch and area of missing or flaking plaster — the wall surface must end up perfectly uniform and intact, matching the surrounding color and texture, with NO crack or damage visible anywhere. Remove ALL dead, dry, wilted, or overgrown weeds, wild plants and dead climbing vines from the walls and ground. Repair any broken, cracked or missing window glass. Remove parked cars, trash bins, cables, satellite dishes, clutter and any temporary object blocking the view of the building. Clean the facade thoroughly, removing all dirt, mold and grime. KEEP EXACTLY AS-IS: the building structure, roofline, all windows and doors (position, size, count), and the camera angle. The result must look like a freshly renovated, impeccably maintained building. Photorealistic, 8k.",
};

const GARDEN_REPAIR = "Also repair any visible damage on the surrounding walls, windows or structure (broken glass, cracks, peeling paint, moss, decay, rust) and remove any wild, overgrown or dead climbing vines and vegetation growing on the windows, walls or facade, so the result looks coherently upgraded — keep the same structure, position and size, just restore its condition. STRICT RULES: preserve the existing layout boundaries, any visible building structure, paths orientation and the camera angle/perspective. Do NOT add or remove any building structure. Photorealistic, 8k.";
const STYLE_PROMPTS_GIARDINO: Record<string, string> = {
  modern: `Edit this photo of a garden/outdoor space: COMPLETELY REDESIGN it in a Modern Minimalist landscaping style. MANDATORY: replace the existing lawn/planting with a clean geometric layout — sharp-edged lawn panels or gravel beds, structured low hedges, a minimal palette of architectural plants (ornamental grasses, boxwood balls), clean concrete or large-format paving pathways, sleek modern outdoor furniture. Remove ALL wild grass, weeds, clutter, garden tools and mismatched pots — the transformation must be clearly visible, not a subtle tweak. ${GARDEN_REPAIR}`,
  nordic: `Edit this photo of a garden/outdoor space: COMPLETELY REDESIGN it in a Natural Woodland-inspired style. MANDATORY: introduce informal native planting drifts, birch or light-bark trees, ornamental grasses and wildflower patches, a natural gravel or bark path, soft dappled light feel. Remove ALL clutter, tools, dead plants and artificial/urban elements — the transformation must be clearly visible, not a subtle tweak. ${GARDEN_REPAIR}`,
  industrial: `Edit this photo of a garden/outdoor space: COMPLETELY REDESIGN it in a Lush Luxury garden style. MANDATORY: fill the space with dense, elegant, perfectly manicured greenery, refined natural stone pathways, integrated ambient garden lighting, upscale outdoor lounge furniture with premium fabrics. Remove ALL clutter, tools, weeds and low-quality or mismatched elements — the transformation must be clearly visible, not a subtle tweak. ${GARDEN_REPAIR}`,
  boho: `Edit this photo of a garden/outdoor space: COMPLETELY REDESIGN it in a Mediterranean garden style. MANDATORY: add mature olive trees, fragrant lavender bushes, large terracotta pots with vibrant flowers, a warm gravel or stone ground cover, a rustic stone pathway, and a wooden pergola with climbing bougainvillea or grapevines. Remove ALL clutter, tools, weeds and modern/urban elements that clash with the style — the transformation must be clearly visible, not a subtle tweak. ${GARDEN_REPAIR}`,
  daynight: "Analyze the lighting in this garden/outdoor photo. If daytime: convert to nighttime — dark sky, warm garden lighting ON (string lights, path lighting, uplighting on trees and plants). If nighttime: convert to daytime — bright natural sunlight, blue sky. CRITICAL: do NOT add, remove or move any plant, structure, furniture or path. ONLY change lighting and sky. Photorealistic, 8k.",
  empty: "Edit this photo to FULLY TIDY UP and restore the garden to a perfectly maintained condition. MANDATORY: completely remove ALL weeds, wild grass, dry thistles and overgrown wild plants — the lawn must become a uniform, evenly mown, healthy green lawn with NO patches of dirt, weeds or dead grass visible anywhere. Clear all walkways and paths completely of grass, weeds and debris growing through the cracks. Remove all garden tools, wheelbarrows, trash, litter, cans, bags and clutter lying on the ground. Trim any overgrown hedges or bushes neatly. KEEP EXACTLY AS-IS: any visible building structure, the layout, paths orientation, existing healthy trees and flower pots, and the camera angle. The result must look like a freshly tended, immaculately maintained garden. Photorealistic, 8k.",
};

// Vietare qualsiasi testo: i modelli a volte inventano scritte su poster e insegne.
const NO_TEXT = ' ABSOLUTELY NO TEXT: do not render any letters, words, writing, captions, signage, neon signs, posters with text, logos, brand names, watermarks, or numbers anywhere in the image. Wall art and decor must be purely abstract or pictorial with zero text.';

const LIGHTING_LOCK = 'This is a LIGHTING-ONLY edit. DO NOT remove, add, move, resize, reshape, recolor, or alter ANY object in the scene — every piece of furniture, wall, ceiling, floor, door, window, curtain, rug, lamp, painting, shelf, plant, and decorative item must remain EXACTLY as in the original photo with identical shape, position, size, color, material, and texture. DO NOT change the camera angle, perspective, framing, or composition in any way.';

// Viste: stesse di Foto AI (src/lib/staging.ts STAGING_ANGLES), avvolte nel modello "nuova inquadratura".
export const ANGLES: { id: string; label: string; prompt: string }[] = [
  { id: 'night', label: 'Notte', prompt: `${LIGHTING_LOCK} Transform to nighttime — replace sky with deep dark-blue night sky with subtle stars. ALL visible light fixtures (chandeliers, table lamps, bedside lamps, wall sconces, floor lamps, ceiling lights, spotlights, outdoor lanterns, garden lights) MUST be turned ON emitting warm realistic light with soft halos and proper light falloff on nearby surfaces. Windows should show warm interior glow. Deep natural shadows, soft ambient fill. Every single structural and decorative element must be preserved pixel-for-pixel. Photorealistic result.` },
  { id: 'day', label: 'Giorno pieno', prompt: `${LIGHTING_LOCK} Transform this scene to BRIGHT MIDDAY DAYLIGHT. The sky visible through windows must be vivid blue with white clouds. Intense natural sunlight floods through every window creating strong, crisp sun beams and well-defined shadows on floors and walls. The overall exposure must be significantly BRIGHTER than the original — lift shadows aggressively, fill dark corners with bounced daylight, increase ambient brightness across the entire frame. All artificial lights (lamps, sconces, ceiling fixtures) should be OFF — the room is lit entirely by abundant natural sunlight. Surfaces should appear warm and sun-kissed. The transformation must be dramatic and unmistakable — the viewer should immediately perceive this as a sun-drenched daytime scene. Every single structural and decorative element must be preserved pixel-for-pixel. Photorealistic result.` },
  { id: 'closeup', label: 'Dettaglio', prompt: 'Ricrea un dettaglio ravvicinato (close-up) dell’elemento principale di questa stanza. Avvicinati significativamente mostrando i dettagli dei materiali, le texture e le finiture. Mantieni gli stessi colori e materiali. Risultato fotorealistico.' },
  { id: 'top', label: 'Dall’alto', prompt: 'Ricrea questa stessa stanza vista dall’alto, con una prospettiva a volo d’uccello (bird’s eye view). Mostra il pavimento e i mobili visti dal soffitto, guardando in basso con un angolo di circa 90 gradi. Mantieni gli stessi mobili, colori e materiali. Risultato fotorealistico.' },
  { id: 'low', label: 'Dal basso', prompt: 'Ricrea questa stessa stanza da un’angolazione bassa (low angle), con la camera posizionata vicino al pavimento e rivolta verso l’alto. I mobili appaiono più imponenti e il soffitto è ben visibile. Mantieni gli stessi mobili, colori e materiali. Risultato fotorealistico.' },
  { id: 'wide', label: 'Grandangolo', prompt: 'Ricrea questa stessa stanza con un obiettivo grandangolare (ultra-wide angle lens, 14mm). Mostra una visuale molto ampia che include più pareti e angoli della stanza. La distorsione prospettica tipica del grandangolo deve essere visibile. Mantieni gli stessi mobili, colori e materiali. Risultato fotorealistico.' },
];

const PLANIMETRIA_BASE = "This image is a 2D architectural floor plan (planimetria). Redraw it as a clean, elegant, COLORED and FURNISHED 2D floor plan seen strictly from directly above (top-down orthographic view, NO perspective, NO 3D, NO isometric, NO tilt). ABSOLUTELY CRITICAL — preserve the geometry EXACTLY: keep the same outer footprint and aspect ratio, and keep every interior wall, every separate room, the corridor/hallway, and all door and window openings in the IDENTICAL position, size, count and proportion as the input. Do NOT add, remove, merge, split, move, rotate or resize any room, wall, corridor or opening. Trace the original walls precisely. Only ADD, inside the existing rooms: realistic per-room floor colors and materials (wood, tile, stone), neat top-view furniture (beds, sofas, dining table and chairs, kitchen counters and appliances, bathroom fixtures, wardrobes), rugs and soft drop shadows. Thin crisp dark walls, light rooms. Output: a professional, readable real-estate 2D rendered floor plan with the SAME layout as the original.";
const FURNISH: Record<string, string> = {
  modern: ' Furnish (top-view) in a clean modern contemporary style: neutral palette with accent colors, minimalist pieces, wood and tile floors.',
  nordic: ' Furnish (top-view) in a Scandinavian Nordic style: light oak/birch wood, white and grey palette, minimal functional pieces, cozy uncluttered look.',
  industrial: ' Furnish (top-view) in a luxury contemporary style: marble and travertine, brass accents, dark walnut wood, elegant upscale textures.',
  boho: ' Furnish (top-view) in a bohemian style: rattan and wicker, natural wood, indoor plants, earthy tones, eclectic patterns.',
};

// Stessa logica di buildFinalPrompt delle edge function: planimetria > vista > testo libero
// (con la protezione adatta alla scena) > stile preset.
export function buildStagingPrompt(o: { style?: string | null; customPrompt?: string | null; angle?: string | null; planimetria?: boolean; scene?: SceneType }): string {
  const scene = o.scene ?? 'interno';
  if (o.planimetria) return PLANIMETRIA_BASE + (FURNISH[o.style || ''] || FURNISH.modern) + NO_TEXT;
  const styles = scene === 'esterno' ? STYLE_PROMPTS_ESTERNO : scene === 'giardino' ? STYLE_PROMPTS_GIARDINO : STYLE_PROMPTS;
  const custom = o.customPrompt?.trim();
  const angle = ANGLES.find(a => a.id === o.angle);
  if (angle) {
    return `ROOM ANALYSIS REQUIRED: Study every detail — furniture pieces, materials, colors, textures, wall finishes, window placement, door positions, architectural features, lighting fixtures, decorative objects. TASK: Regenerate this IDENTICAL room from a new camera position: ${angle.prompt}. Every object must appear in the same position relative to the room. Same furniture, same colors, same materials, same lighting conditions, same time of day. FORBIDDEN: adding new objects, removing existing objects, changing any material or color, altering room dimensions, modifying architectural features. Output: photorealistic interior photograph, 8K, consistent with input image lighting.${NO_TEXT}`;
  }
  if (custom) {
    if (scene === 'esterno') return `BUILDING LOCKED: Preserve EXACTLY the house facade, roofline, windows, doors, walls, materials, colors, and the camera angle/perspective. FORBIDDEN: changing the building's structure, adding new floors, altering the facade shape. ALLOWED: adding or modifying garden elements, pool, terrace furniture, landscaping, driveway, plants as requested. USER EDIT REQUEST (apply in any language): "${custom}". Apply the requested changes to the surroundings while keeping the building itself identical. Photorealistic result, 8K architectural photography.${NO_TEXT}`;
    if (scene === 'giardino') return `GARDEN EDIT: Preserve the existing layout, any visible building structure, paths, boundaries and the camera angle/perspective exactly. ALLOWED: freely adding or modifying plants, furniture, pool, decking, lighting as requested. USER EDIT REQUEST (apply in any language): "${custom}". Photorealistic result, 8K outdoor photography.${NO_TEXT}`;
    return `ARCHITECTURE LOCKED: Preserve EXACTLY — every wall, door, window, arch, column, ceiling, floor. Same proportions, same perspective, same camera angle. FORBIDDEN: adding/removing doors, windows, openings, rooms; changing room dimensions or perspective. USER EDIT REQUEST (apply in any language): "${custom}". Apply the requested changes while preserving room structure and architectural elements. Photorealistic result, 8K interior photography.${NO_TEXT}`;
  }
  return (styles[o.style || ''] || styles.modern) + NO_TEXT;
}
